import { VarynthModule } from "./types";

export const modules: VarynthModule[] = [
  // --- SYSTEM APPS ---
  {
    id: "projects",
    name: "Projects",
    description: "Hub principal de projetos. Workspaces com tarefas, notas, arquivos, timeline e Athena integrada.",
    icon: "📁",
    layer: "system",
    category: "gestao",
    color: "cyan",
    href: "/projects",
    status: "active",
    tags: ["projetos", "gestao", "workspace", "kanban"],
    version: "1.0.0",
    badge: "Principal",
  },
  {
    id: "vault",
    name: "Vault",
    description: "Biblioteca pessoal e segundo cérebro relacional para artigos, livros, leis, links e anotações.",
    icon: "📚",
    layer: "system",
    category: "conhecimento",
    color: "violet",
    href: "/modules/vault",
    status: "wip",
    tags: ["biblioteca", "segundo-cerebro", "pdf", "referencias"],
    version: "0.1.0",
  },
  {
    id: "chronos",
    name: "Chronos",
    description: "Gestão temporal avançada com calendário, rotinas, histórico de atividades e linha do tempo.",
    icon: "⏳",
    layer: "system",
    category: "produtividade",
    color: "orange",
    href: "/modules/chronos",
    status: "wip",
    tags: ["calendario", "tempo", "rotina", "prazos"],
    version: "0.1.0",
  },
  {
    id: "people",
    name: "People",
    description: "Gestão de colaboradores, contatos e redes de trabalho vinculados a projetos.",
    icon: "👥",
    layer: "system",
    category: "gestao",
    color: "emerald",
    href: "/modules/people",
    status: "wip",
    tags: ["colaboradores", "equipe", "contatos"],
    version: "0.1.0",
  },
  {
    id: "labs",
    name: "Labs & Graveyard",
    description: "Incubadora de ideias e experimentos (Ideia → Protótipo → Projeto) e retrospectiva de aprendizados.",
    icon: "🧪",
    layer: "system",
    category: "produtividade",
    color: "amber",
    href: "/modules/labs",
    status: "wip",
    tags: ["ideias", "experimentos", "retrospectiva"],
    version: "0.1.0",
  },

  // --- PERSONAL APPS ---
  {
    id: "athena",
    name: "Athena AI",
    description: "Inteligência Artificial integrada transversalmente ao VARYNTH para automação e suporte a decisões.",
    icon: "🦉",
    layer: "personal",
    category: "inteligencia",
    color: "violet",
    href: "/modules/athena",
    status: "active",
    tags: ["ia", "chat", "automacao", "copilot"],
    version: "0.2.0",
    badge: "IA Integrada",
  },
  {
    id: "codex",
    name: "Codex",
    description: "Ambiente jurídico completo com jurisprudência, doutrina, fichamentos e Argument Arena.",
    icon: "⚖️",
    layer: "personal",
    category: "juridico",
    color: "cyan",
    href: "/modules/codex",
    status: "wip",
    tags: ["direito", "jurisprudencia", "argument-arena", "teses"],
    version: "0.1.0",
  },
  {
    id: "research",
    name: "Research",
    description: "Pesquisa acadêmica estruturada com hipóteses, metodologia e Evidence Board para artigos e teses.",
    icon: "🔬",
    layer: "personal",
    category: "pesquisa",
    color: "violet",
    href: "/modules/research",
    status: "wip",
    tags: ["academia", "artigos", "evidence-board", "fontes"],
    version: "0.1.0",
  },
  {
    id: "opportunities",
    name: "Opportunities",
    description: "Radar de editais, chamadas acadêmicas, concursos, bolsas e prêmios com pipeline de submissão.",
    icon: "🏆",
    layer: "personal",
    category: "gestao",
    color: "amber",
    href: "/modules/opportunities",
    status: "wip",
    tags: ["editais", "concursos", "bolsas", "premios"],
    version: "0.1.0",
  },
  {
    id: "forge",
    name: "Forge",
    description: "Ambiente de desenvolvimento com Monaco Editor, árvore de arquivos, documentação e Git.",
    icon: "🛠️",
    layer: "personal",
    category: "desenvolvimento",
    color: "orange",
    href: "/modules/forge",
    status: "wip",
    tags: ["editor", "codigo", "monaco", "git"],
    version: "0.1.0",
  },
  {
    id: "ligahub",
    name: "LigaHub",
    description: "Sistema operacional completo para gestão da Liga Acadêmica (membros, presença, financeiro).",
    icon: "🏛️",
    layer: "personal",
    category: "gestao",
    color: "cyan",
    href: "http://localhost:8000",
    status: "active",
    tags: ["gestao", "academia", "qr-code", "liga"],
    version: "1.0.0",
  },
];
