import { VarynthModule } from "./types";

export const modules: VarynthModule[] = [
  // --- SYSTEM APPS ---
  {
    id: "projects",
    name: "Projects",
    description: "Hub principal de projetos. Workspaces com tarefas, notas, arquivos, timeline e Athena integrada.",
    icon: "📁",
    layer: "system",
    category: "gestao",
    color: "cyan",
    href: "/projects",
    status: "active",
    tags: ["projetos", "gestao", "workspace", "kanban"],
    version: "1.0.0",
    badge: "Principal",
  },
  {
    id: "graph",
    name: "Graph Epistêmico",
    description: "Visualizador espacial de conexões entre projetos, vault, teses, evidências e código.",
    icon: "🕸️",
    layer: "system",
    category: "conhecimento",
    color: "cyan",
    href: "/modules/graph",
    status: "active",
    tags: ["grafo", "rede", "conexoes", "visualizador"],
    version: "1.0.0",
    badge: "Novo",
  },
  {
    id: "vault",
    name: "Vault",
    description: "Biblioteca pessoal e segundo cérebro relacional para artigos, livros, leis, links e anotações.",
    icon: "📚",
    layer: "system",
    category: "conhecimento",
    color: "violet",
    href: "/modules/vault",
    status: "active",
    tags: ["biblioteca", "segundo-cerebro", "pdf", "referencias"],
    version: "1.0.0",
  },
  {
    id: "chronos",
    name: "Chronos",
    description: "Gestão temporal avançada com calendário, rotinas, foco e linha do tempo histórica.",
    icon: "⏳",
    layer: "system",
    category: "produtividade",
    color: "orange",
    href: "/modules/chronos",
    status: "active",
    tags: ["calendario", "tempo", "rotina", "prazos"],
    version: "1.0.0",
  },
  {
    id: "people",
    name: "People",
    description: "Gestão de colaboradores e permissões granulares de acesso isolado por projeto.",
    icon: "👥",
    layer: "system",
    category: "gestao",
    color: "emerald",
    href: "/modules/people",
    status: "active",
    tags: ["colaboradores", "equipe", "contatos"],
    version: "1.0.0",
  },
  {
    id: "labs",
    name: "Labs & Graveyard",
    description: "Incubadora de ideias com 'Promote to Project' e memorial de aprendizados de projetos descontinuados.",
    icon: "🧪",
    layer: "system",
    category: "produtividade",
    color: "amber",
    href: "/modules/labs",
    status: "active",
    tags: ["ideias", "experimentos", "retrospectiva"],
    version: "1.0.0",
  },

  // --- PERSONAL APPS ---
  {
    id: "athena",
    name: "Athena AI",
    description: "Inteligência Artificial transversal e Command Center NLP com visibilidade total do VARYNTH OS.",
    icon: "🦉",
    layer: "personal",
    category: "inteligencia",
    color: "violet",
    href: "/modules/athena",
    status: "active",
    tags: ["ia", "chat", "automacao", "copilot"],
    version: "4.0.0",
    badge: "IA Transversal",
  },
  {
    id: "codex",
    name: "Codex & Arena",
    description: "Ambiente jurídico dialético com a Argument Arena, jurisprudência, doutrina e fichamentos.",
    icon: "⚖️",
    layer: "personal",
    category: "juridico",
    color: "cyan",
    href: "/modules/codex",
    status: "active",
    tags: ["direito", "jurisprudencia", "argument-arena", "teses"],
    version: "1.0.0",
  },
  {
    id: "research",
    name: "Research & Board",
    description: "Pesquisa acadêmica estruturada com Evidence Board probatório para artigos e publicações Qualis.",
    icon: "🔬",
    layer: "personal",
    category: "pesquisa",
    color: "violet",
    href: "/modules/research",
    status: "active",
    tags: ["academia", "artigos", "evidence-board", "fontes"],
    version: "1.0.0",
  },
  {
    id: "opportunities",
    name: "Opportunities",
    description: "Radar de editais, bolsas PIBIC, concursos e premiações com Pipeline Kanban de submissão.",
    icon: "🏆",
    layer: "personal",
    category: "gestao",
    color: "amber",
    href: "/modules/opportunities",
    status: "active",
    tags: ["editais", "concursos", "bolsas", "premios"],
    version: "1.0.0",
  },
  {
    id: "forge",
    name: "Forge Studio",
    description: "Web IDE com editor multi-linguagem, terminal interativo JS/Python/SQL e templates.",
    icon: "🛠️",
    layer: "personal",
    category: "desenvolvimento",
    color: "orange",
    href: "/modules/forge",
    status: "active",
    tags: ["editor", "codigo", "ide", "runner"],
    version: "1.0.0",
  },
  {
    id: "ligahub",
    name: "LigaHub",
    description: "Sistema operacional completo para gestão da Liga Acadêmica (membros, presença, financeiro).",
    icon: "🏛️",
    layer: "personal",
    category: "gestao",
    color: "cyan",
    href: "http://localhost:8000",
    status: "active",
    tags: ["gestao", "academia", "qr-code", "liga"],
    version: "1.0.0",
  },
];
