import "server-only";
import { createCipheriv, createDecipheriv, createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { getVarynthOrigin } from "@/lib/config/platform";

export interface GoogleTokenSet { access_token: string; refresh_token?: string; expires_at: number; scope?: string; token_type?: string; }
const DATA_DIR = path.join(process.cwd(), ".varynth-data");
const TOKEN_FILE = path.join(DATA_DIR, "google-calendar.tokens.enc");
const SCOPE = "https://www.googleapis.com/auth/calendar.readonly";

export function oauthConfig() {
  const clientId = process.env.GOOGLE_CALENDAR_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CALENDAR_CLIENT_SECRET;
  const encryptionSecret = process.env.VARYNTH_TOKEN_ENCRYPTION_KEY;
  return { clientId, clientSecret, encryptionSecret, configured: Boolean(clientId && clientSecret && encryptionSecret), missing: [!clientId && "GOOGLE_CALENDAR_CLIENT_ID", !clientSecret && "GOOGLE_CALENDAR_CLIENT_SECRET", !encryptionSecret && "VARYNTH_TOKEN_ENCRYPTION_KEY"].filter(Boolean) as string[] };
}
function key() { const secret = oauthConfig().encryptionSecret; if (!secret) throw new Error("Chave de criptografia não configurada."); return createHash("sha256").update(secret).digest(); }
function seal(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString("base64url"); }
function open(value: string) { const raw = Buffer.from(value, "base64url"); if (raw.length < 29) throw new Error("Dado protegido inválido."); const decipher = createDecipheriv("aes-256-gcm", key(), raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString("utf8"); }
export function createOAuthRequest(origin: string) { const config = oauthConfig(); if (!config.configured) throw new Error(`Configuração incompleta: ${config.missing.join(", ")}`); const state = randomBytes(24).toString("base64url"); const verifier = randomBytes(48).toString("base64url"); const challenge = createHash("sha256").update(verifier).digest("base64url"); const redirectUri = `${getVarynthOrigin(origin)}/api/integrations/google-calendar/callback`; const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.search = new URLSearchParams({ client_id: config.clientId!, redirect_uri: redirectUri, response_type: "code", scope: SCOPE, access_type: "offline", prompt: "consent", state, code_challenge: challenge, code_challenge_method: "S256" }).toString(); return { url: url.toString(), cookie: seal(JSON.stringify({ state, verifier, redirectUri, createdAt: Date.now() })) }; }
export function readOAuthCookie(value: string) { return JSON.parse(open(value)) as { state: string; verifier: string; redirectUri: string; createdAt: number }; }
export function safeStateEqual(a: string, b: string) { const one = Buffer.from(a); const two = Buffer.from(b); return one.length === two.length && timingSafeEqual(one, two); }
export async function exchangeCode(code: string, verifier: string, redirectUri: string) { const config = oauthConfig(); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: config.clientId!, client_secret: config.clientSecret!, redirect_uri: redirectUri, grant_type: "authorization_code", code_verifier: verifier }), cache: "no-store" }); if (!response.ok) throw new Error(`Google recusou a autenticação (${response.status}).`); const raw = await response.json() as { access_token: string; refresh_token?: string; expires_in: number; scope?: string; token_type?: string }; const tokens = { ...raw, expires_at: Date.now() + raw.expires_in * 1000 - 60_000 }; await saveTokens(tokens); }
async function saveTokens(tokens: GoogleTokenSet) { await mkdir(DATA_DIR, { recursive: true }); await writeFile(TOKEN_FILE, seal(JSON.stringify(tokens)), { encoding: "utf8", mode: 0o600 }); }
export async function loadTokens(): Promise<GoogleTokenSet | undefined> { try { return JSON.parse(open(await readFile(TOKEN_FILE, "utf8"))); } catch { return undefined; } }
async function validAccessToken() { let tokens = await loadTokens(); if (!tokens) throw new Error("Google Calendar não conectado."); if (tokens.expires_at > Date.now()) return tokens.access_token; if (!tokens.refresh_token) throw new Error("A conexão expirou e precisa ser refeita."); const config = oauthConfig(); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: config.clientId!, client_secret: config.clientSecret!, refresh_token: tokens.refresh_token, grant_type: "refresh_token" }), cache: "no-store" }); if (!response.ok) throw new Error("Não foi possível renovar a conexão com o Google."); const raw = await response.json() as { access_token: string; expires_in: number; scope?: string; token_type?: string }; tokens = { ...tokens, ...raw, expires_at: Date.now() + raw.expires_in * 1000 - 60_000 }; await saveTokens(tokens); return tokens.access_token; }
export async function fetchCalendarEvents(windowDays = 45) { const token = await validAccessToken(); const url = new URL("https://www.googleapis.com/calendar/v3/calendars/primary/events"); url.search = new URLSearchParams({ timeMin: new Date().toISOString(), timeMax: new Date(Date.now() + Math.min(Math.max(windowDays, 1), 90) * 86_400_000).toISOString(), singleEvents: "true", orderBy: "startTime", maxResults: "250" }).toString(); const response = await fetch(url, { headers: { authorization: `Bearer ${token}` }, cache: "no-store" }); if (!response.ok) throw new Error(`Falha ao ler o calendário (${response.status}).`); const data = await response.json() as { items?: Array<{ id: string; summary?: string; start?: { dateTime?: string; date?: string }; end?: { dateTime?: string; date?: string }; htmlLink?: string; location?: string; description?: string; updated?: string }> }; return (data.items || []).filter((item) => item.id && item.start && item.end).map((item) => ({ id: item.id, summary: item.summary || "Evento sem título", start: item.start!.dateTime || item.start!.date!, end: item.end!.dateTime || item.end!.date!, url: item.htmlLink, location: item.location, description: item.description, calendarId: "primary", updatedAt: item.updated })); }
export async function disconnectGoogleCalendar() { try { await unlink(TOKEN_FILE); } catch { /* já desconectado */ } }
