import assert from "node:assert/strict";
import { PermissionPolicyEngine } from "@/lib/permissions/permission-policy";
import { authorizeEuterpeProposal, euterpeManifest, interpretEuterpeRequest } from "./euterpe";

const context = { track: { id: "t1", name: "Noite", artist: "X" }, dna: { trackId: "t1", schemaVersion: 2 as const, status: "PARTIAL" as const, visualTags: ["dark"], intensity: 0.2, calmness: 0.8 }, preferences: [], memories: [] };
const proposal = interpretEuterpeRequest("Faça o visual da faixa escuro", context);
assert.equal(proposal.proposal?.kind, "visual-profile");
assert.equal(euterpeManifest.id, "euterpe");
const policy = new PermissionPolicyEngine();
const decision = authorizeEuterpeProposal(policy, proposal.proposal!);
assert.equal(decision.policy, "CONFIRM");
assert.equal(authorizeEuterpeProposal(policy, { kind: "preference", key: "x", value: "jazz" }).policy, "CONFIRM");
const answer = interpretEuterpeRequest("Oi", context).response;
assert.match(answer, /Euterpe/); assert.match(answer, /Noite/);
const broadVisual = interpretEuterpeRequest("Quero uma atmosfera cinematográfica quente", context);
assert.equal(broadVisual.proposal?.kind, "visual-profile", "Broader visual language should create a reviewable proposal");
const memoryAware = interpretEuterpeRequest("Que estilo combina comigo?", { ...context, preferences: [{ id: "p1", key: "style", value: "jazz", confidence: 1, source: "explicit", updatedAt: "2026-09-22" }], memories: [{ id: "m1", kind: "favorite", value: "trilhas instrumentais", createdAt: "2026-09-22" }] });
assert.match(memoryAware.response, /jazz, trilhas instrumentais/, "Euterpe should use both scoped preference and music-memory context");
const conversational = interpretEuterpeRequest("Por quê?", context, [{ sender: "user", text: "Analise a faixa" }, { sender: "curator", text: "A faixa Noite tem tags dark no Music DNA." }, { sender: "user", text: "Por quê?" }]);
assert.match(conversational.response, /retomando|Music DNA/, "Follow-ups should use the immediate conversation rather than generic boilerplate");
const unsupportedListening = interpretEuterpeRequest("Analise a faixa", { ...context, dna: undefined });
assert.match(unsupportedListening.response, /não há Music DNA suficiente/i, "No acoustic facts should be fabricated without analysis data");
console.log("Euterpe identity, context, structured proposals, and confirmation policy passed.");
