"use client";

import { useState } from "react";
import { DrumLane, DrumPattern, DrumStep, createDrumPattern, drumLanes, drumPatternToNotes } from "@/lib/studio/audio/drum-sequencer-domain";
import { MusicProjectState } from "@/lib/studio/audio/music-domain";

const LABELS: Record<DrumLane, string> = { kick: "Kick", snare: "Snare", hat: "Hi-hat", clap: "Clap", tom: "Tom", perc: "Percussão" };

export function DrumSequencerPanel({ patterns, onPatternsChange, music, onMusicChange }: { patterns: DrumPattern[]; onPatternsChange: (patterns: DrumPattern[]) => void; music: MusicProjectState; onMusicChange: (music: MusicProjectState) => void }) {
  const [selectedId, setSelectedId] = useState(patterns[0]?.id || "");
  const [message, setMessage] = useState("");
  const selected = patterns.find((pattern) => pattern.id === selectedId) || patterns[0];
  const create = () => {
    const pattern = createDrumPattern({ id: `drum-${Date.now()}`, name: `Beat ${patterns.length + 1}`, steps: 16, subdivision: 16 });
    onPatternsChange([...patterns, pattern]); setSelectedId(pattern.id); setMessage("Padrão criado e salvo no projeto.");
  };
  const update = (transform: (pattern: DrumPattern) => DrumPattern) => { if (selected) onPatternsChange(patterns.map((pattern) => pattern.id === selected.id ? transform(selected) : pattern)); };
  const toggle = (lane: DrumLane, index: number) => update((pattern) => { const steps = [...pattern.lanes[lane]]; steps[index] = { ...steps[index], active: !steps[index].active }; return { ...pattern, lanes: { ...pattern.lanes, [lane]: steps } }; });
  const patchStep = (lane: DrumLane, index: number, patch: Partial<DrumStep>) => update((pattern) => { const steps = [...pattern.lanes[lane]]; steps[index] = { ...steps[index], ...patch }; return { ...pattern, lanes: { ...pattern.lanes, [lane]: steps } }; });
  const sendToComposition = () => {
    if (!selected) return;
    const notes = drumPatternToNotes(selected, music.tempoMap);
    const existing = music.notes.filter((note) => note.drum?.patternId !== selected.id);
    onMusicChange({ ...music, notes: [...existing, ...notes] });
    setMessage(`${notes.length} hit(s) enviados para o Piano Roll e para a estrutura musical.`);
  };
  return <section className="flex h-full flex-col overflow-auto bg-[#0b0c16] p-5 text-slate-200" aria-label="Drum Sequencer"><header className="mb-4 flex flex-wrap items-center justify-between gap-3 border-b border-[#252844] pb-4"><div><h2 className="text-sm font-bold text-white">Drum Sequencer</h2><p className="mt-1 text-xs text-slate-500">Crie padrões, edite cada hit e envie as batidas à composição musical do projeto.</p></div><div className="flex gap-2"><select aria-label="Padrão de bateria" value={selected?.id || ""} onChange={(event) => setSelectedId(event.target.value)} className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-xs text-white">{patterns.map((pattern) => <option key={pattern.id} value={pattern.id}>{pattern.name}</option>)}</select><button type="button" onClick={create} className="rounded bg-fuchsia-700 px-3 py-1.5 text-xs font-semibold text-white">Novo padrão</button></div></header>
    {!selected ? <p className="text-xs text-slate-500">Crie um padrão para começar.</p> : <><div className="mb-3 flex flex-wrap items-end gap-3"><label className="text-[10px] text-slate-400">Nome<input aria-label="Nome do padrão" value={selected.name} onChange={(event) => update((pattern) => ({ ...pattern, name: event.target.value }))} className="mt-1 block rounded border border-[#303650] bg-[#111528] px-2 py-1 text-xs text-white" /></label><label className="text-[10px] text-slate-400">Passos<select aria-label="Quantidade de passos" value={selected.steps} onChange={(event) => update((pattern) => createDrumPattern({ ...pattern, steps: Number(event.target.value) }))} className="mt-1 block rounded border border-[#303650] bg-[#111528] px-2 py-1 text-xs text-white">{[4, 8, 16, 32].map((count) => <option key={count}>{count}</option>)}</select></label><label className="text-[10px] text-slate-400">Subdivisão<select aria-label="Subdivisão" value={selected.subdivision} onChange={(event) => update((pattern) => createDrumPattern({ ...pattern, subdivision: Number(event.target.value) as DrumPattern["subdivision"] }))} className="mt-1 block rounded border border-[#303650] bg-[#111528] px-2 py-1 text-xs text-white">{[4, 8, 16, 32].map((count) => <option key={count}>{count}</option>)}</select></label><label className="text-[10px] text-slate-400">Swing {Math.round(selected.swing * 100)}%<input aria-label="Swing" type="range" min="0" max="1" step="0.01" value={selected.swing} onChange={(event) => update((pattern) => ({ ...pattern, swing: Number(event.target.value) }))} className="ml-2 align-middle" /></label></div>
    <div className="min-w-max overflow-auto rounded border border-[#252844] bg-[#0c0f1d] p-3"><div className="space-y-2">{drumLanes().map((lane) => <div key={lane} className="flex items-center gap-2"><span className="w-20 text-[10px] font-semibold text-slate-400">{LABELS[lane]}</span><div className="flex gap-1">{selected.lanes[lane].map((step, index) => <button key={index} type="button" aria-pressed={step.active} aria-label={`${LABELS[lane]} passo ${index + 1}`} onClick={() => toggle(lane, index)} onContextMenu={(event) => { event.preventDefault(); patchStep(lane, index, { velocity: step.velocity >= 127 ? 40 : step.velocity + 16 }); }} title={`Velocity ${step.velocity} · Probabilidade ${Math.round(step.probability * 100)}% · clique direito altera velocity`} className={`h-7 w-7 rounded-sm border text-[9px] ${step.active ? "border-fuchsia-300 bg-fuchsia-600 text-white" : "border-[#303650] bg-[#15192b] text-slate-600"}`}>{index + 1}</button>)}</div></div>)}</div><p className="mt-3 text-[9px] text-slate-600">Clique para ativar hits. Clique direito sobre um hit ativo para alterar sua velocity.</p></div>
    <div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={sendToComposition} disabled={!Object.values(selected.lanes).some((lane) => lane.some((step) => step.active))} className="rounded bg-cyan-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Enviar para composição</button><button type="button" onClick={() => { onPatternsChange(patterns.filter((pattern) => pattern.id !== selected.id)); setSelectedId(patterns.find((pattern) => pattern.id !== selected.id)?.id || ""); setMessage("Padrão removido do projeto."); }} className="rounded bg-rose-950 px-3 py-2 text-xs text-rose-200">Remover padrão</button></div></>}
    {message && <p role="status" className="mt-3 text-[10px] text-cyan-200">{message}</p>}</section>;
}
