"use client";
import { useState } from "react";
import { SamplerDefinition, validateSamplerDefinition } from "@/lib/studio/audio/sampler-domain";

export function SamplerPanel({ definitions, onChange }: { definitions: SamplerDefinition[]; onChange: (definitions: SamplerDefinition[]) => void }) {
  const [name, setName] = useState(""); const [assetId, setAssetId] = useState(""); const [rootMidi, setRootMidi] = useState(60); const [minMidi, setMinMidi] = useState(0); const [maxMidi, setMaxMidi] = useState(127); const [message, setMessage] = useState<string>();
  const create = () => { try { const definition = validateSamplerDefinition({ id: `sampler-${Date.now()}`, name, assetId, rootMidi, minMidi, maxMidi, envelope: { attackMs: 5, decayMs: 80, sustain: 0.8, releaseMs: 120 }, gain: 1 }); onChange([...definitions, definition]); setName(""); setAssetId(""); setMessage("Sampler salvo no projeto."); } catch (error) { setMessage(error instanceof Error ? error.message : "Definição de sampler inválida."); } };
  return <section className="mt-5 max-w-3xl rounded-lg border border-fuchsia-500/30 bg-fuchsia-500/5 p-3" aria-label="Sampler"><h3 className="text-xs font-semibold text-fuchsia-200">Sampler local</h3><p className="mt-1 text-[10px] text-slate-400">Mapeie um asset de áudio real para tocar melodicamente. O asset não é duplicado.</p><div className="mt-3 grid gap-2 md:grid-cols-5"><input aria-label="Nome do sampler" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome" className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-[10px] text-white" /><input aria-label="Asset do sampler" value={assetId} onChange={(event) => setAssetId(event.target.value)} placeholder="assetId" className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-[10px] text-white" /><input aria-label="Root MIDI do sampler" type="number" min="0" max="127" value={rootMidi} onChange={(event) => setRootMidi(Number(event.target.value))} className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-[10px] text-white" /><input aria-label="MIDI mínimo do sampler" type="number" min="0" max="127" value={minMidi} onChange={(event) => setMinMidi(Number(event.target.value))} className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-[10px] text-white" /><input aria-label="MIDI máximo do sampler" type="number" min="0" max="127" value={maxMidi} onChange={(event) => setMaxMidi(Number(event.target.value))} className="rounded border border-[#303650] bg-[#111528] px-2 py-1 text-[10px] text-white" /></div><button type="button" disabled={!name.trim() || !assetId.trim()} onClick={create} className="mt-3 rounded bg-fuchsia-700 px-3 py-1.5 text-[10px] font-semibold text-white disabled:opacity-40">Adicionar sampler</button>{message && <p role="status" className="mt-2 text-[10px] text-fuchsia-200">{message}</p>}<div className="mt-3 space-y-1">{definitions.map((definition) => <div key={definition.id} className="flex items-center justify-between rounded bg-[#111326] px-2 py-1 text-[10px]"><span className="text-slate-200">{definition.name} · {definition.assetId} · C{definition.rootMidi}</span><button type="button" onClick={() => onChange(definitions.filter((item) => item.id !== definition.id))} className="rounded bg-rose-900/60 px-2 py-1 text-rose-200">Remover</button></div>)}</div></section>;
}
