"use client";

import { AudioClip } from "@/lib/studio/audio/types";

export function SpatialAudioPanel({ clips, selectedClipIds, onChange }: { clips: AudioClip[]; selectedClipIds: string[]; onChange: (clipId: string, spatial: NonNullable<AudioClip["spatial"]> | undefined) => void }) {
  const selected = clips.filter((clip) => selectedClipIds.includes(clip.id));
  if (!selected.length) return <section aria-label="Espacialização" className="rounded-lg border border-[#252844] bg-[#111326] p-3 text-xs text-slate-500">Selecione um clip para editar sua posição espacial.</section>;
  const primary = selected[0];
  const spatial = primary.spatial || { x: 0, y: 0, z: 0, refDistance: 1, maxDistance: 10000, rolloffFactor: 1 };
  const update = (key: keyof typeof spatial, value: number) => selected.forEach((clip) => onChange(clip.id, { ...(clip.spatial || spatial), [key]: value }));
  return <section aria-label="Espacialização" className="rounded-lg border border-[#252844] bg-[#111326] p-3 text-xs text-slate-300"><div className="flex items-center justify-between"><h3 className="font-semibold text-white">Espacialização</h3><span className="text-[10px] text-slate-500">{selected.length} clip(s)</span></div><p className="mt-1 text-[10px] text-slate-500">HRTF · distância inverse</p><div className="mt-3 grid grid-cols-3 gap-2">{(["x", "y", "z"] as const).map((key) => <label key={key} className="text-[10px] text-slate-500">{key.toUpperCase()}<input aria-label={`Posição ${key}`} type="number" step="0.1" value={spatial[key]} onChange={(event) => update(key, Number(event.target.value))} className="mt-1 w-full rounded border border-[#303650] bg-[#0b0c16] px-1 py-1 text-white" /></label>)}</div><div className="mt-2 grid grid-cols-3 gap-2"><label className="text-[10px] text-slate-500">Ref.<input aria-label="Distância de referência" type="number" min="0.001" step="0.1" value={spatial.refDistance} onChange={(event) => update("refDistance", Math.max(0.001, Number(event.target.value)))} className="mt-1 w-full rounded border border-[#303650] bg-[#0b0c16] px-1 py-1 text-white" /></label><label className="text-[10px] text-slate-500">Máx.<input aria-label="Distância máxima" type="number" min="0.001" step="1" value={spatial.maxDistance} onChange={(event) => update("maxDistance", Math.max(0.001, Number(event.target.value)))} className="mt-1 w-full rounded border border-[#303650] bg-[#0b0c16] px-1 py-1 text-white" /></label><label className="text-[10px] text-slate-500">Rolloff<input aria-label="Fator de rolloff" type="number" min="0" step="0.1" value={spatial.rolloffFactor} onChange={(event) => update("rolloffFactor", Math.max(0, Number(event.target.value)))} className="mt-1 w-full rounded border border-[#303650] bg-[#0b0c16] px-1 py-1 text-white" /></label></div><button type="button" onClick={() => selected.forEach((clip) => onChange(clip.id, undefined))} className="mt-3 rounded bg-slate-700 px-2 py-1 text-[10px] text-white">Remover espacialização</button></section>;
}
