import { AudioTrack, AudioTimelineMarker } from "./types";

export interface AudioTemplate {
  id: string;
  name: string;
  description: string;
  timelineDurationMs: number;
  initialTracks: AudioTrack[];
  initialMarkers?: AudioTimelineMarker[];
}

export const AUDIO_TEMPLATES: AudioTemplate[] = [
  {
    id: "blank",
    name: "Projeto em Branco",
    description: "Linha do tempo limpa com 1 faixa de áudio e 30 segundos de duração.",
    timelineDurationMs: 30000,
    initialTracks: [
      {
        id: "track-voice-1",
        name: "Voz Principal",
        type: "VOICE",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#3b82f6",
      },
    ],
  },
  {
    id: "podcast",
    name: "Podcast / Entrevista",
    description: "Estrutura pronta para podcast com faixa de apresentador, convidado, trilha e vinhetas.",
    timelineDurationMs: 60000,
    initialTracks: [
      {
        id: "track-host",
        name: "Host (Apresentador)",
        type: "VOICE",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: -0.1,
        clips: [],
        effects: [],
        color: "#3b82f6",
      },
      {
        id: "track-guest",
        name: "Convidado",
        type: "VOICE",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: 0.1,
        clips: [],
        effects: [],
        color: "#06b6d4",
      },
      {
        id: "track-music-bed",
        name: "Trilha de Fundo",
        type: "MUSIC",
        muted: false,
        solo: false,
        volume: 0.6,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#8b5cf6",
      },
      {
        id: "track-sfx-stings",
        name: "Vinhetas & Efeitos",
        type: "SFX",
        muted: false,
        solo: false,
        volume: 0.8,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#f59e0b",
      },
    ],
    initialMarkers: [
      { id: "mark-intro", timeMs: 0, label: "Introdução", color: "#3b82f6" },
      { id: "mark-interview", timeMs: 10000, label: "Início do Diálogo", color: "#10b981" },
      { id: "mark-outro", timeMs: 50000, label: "Encerramento", color: "#ef4444" },
    ],
  },
  {
    id: "narration",
    name: "Locução & Audiolivro",
    description: "Configurado para leitura de textos, pareceres jurídicos e audiolivros com ambiência sutil.",
    timelineDurationMs: 45000,
    initialTracks: [
      {
        id: "track-narration",
        name: "Locução / Narração",
        type: "VOICE",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#3b82f6",
      },
      {
        id: "track-ambience",
        name: "Ambiência Acústica",
        type: "AUDIO",
        muted: false,
        solo: false,
        volume: 0.35,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#64748b",
      },
    ],
  },
  {
    id: "voice-plus-music",
    name: "Voz + Trilha Sonora",
    description: "Composição direta de locução sobreposta com trilha musical de fundo.",
    timelineDurationMs: 30000,
    initialTracks: [
      {
        id: "track-voice",
        name: "Voz",
        type: "VOICE",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#3b82f6",
      },
      {
        id: "track-music",
        name: "Música",
        type: "MUSIC",
        muted: false,
        solo: false,
        volume: 0.5,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#ec4899",
      },
    ],
  },
  {
    id: "soundtrack",
    name: "Trilha Sonora Multicamadas",
    description: "Projeto para arranjo musical com stems de harmonia, melodia, percussão e texturas.",
    timelineDurationMs: 90000,
    initialTracks: [
      {
        id: "track-melody",
        name: "Melodia Principal",
        type: "MUSIC",
        muted: false,
        solo: false,
        volume: 0.9,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#8b5cf6",
      },
      {
        id: "track-harmony",
        name: "Harmonia / Pads",
        type: "MUSIC",
        muted: false,
        solo: false,
        volume: 0.7,
        pan: -0.2,
        clips: [],
        effects: [],
        color: "#a855f7",
      },
      {
        id: "track-percussion",
        name: "Percussão / Batida",
        type: "MUSIC",
        muted: false,
        solo: false,
        volume: 0.85,
        pan: 0.1,
        clips: [],
        effects: [],
        color: "#d946ef",
      },
      {
        id: "track-sfx-riser",
        name: "Efeitos Sonoros",
        type: "SFX",
        muted: false,
        solo: false,
        volume: 0.8,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#f59e0b",
      },
    ],
  },
  {
    id: "sfx-composition",
    name: "Composição de Sound Design",
    description: "4 faixas dedicadas a sobreposição de foley, impactos e efeitos para jogos e cinema.",
    timelineDurationMs: 15000,
    initialTracks: [
      {
        id: "track-foley-1",
        name: "Foley / Movimento",
        type: "SFX",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: -0.3,
        clips: [],
        effects: [],
        color: "#f59e0b",
      },
      {
        id: "track-foley-2",
        name: "Foley / Impactos",
        type: "SFX",
        muted: false,
        solo: false,
        volume: 1.0,
        pan: 0.3,
        clips: [],
        effects: [],
        color: "#d97706",
      },
      {
        id: "track-sub",
        name: "Sub / Graves",
        type: "SFX",
        muted: false,
        solo: false,
        volume: 0.9,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#b45309",
      },
      {
        id: "track-atmos",
        name: "Atmosfera",
        type: "AUDIO",
        muted: false,
        solo: false,
        volume: 0.7,
        pan: 0.0,
        clips: [],
        effects: [],
        color: "#64748b",
      },
    ],
  },
];

