import { effectiveNoteDurationBeats, flattenMusicNotes, MusicProjectState, MusicalNote } from "./music-domain";
const pitchStep: Record<MusicalNote["pitch"], string> = { C: "C", D: "D", E: "E", F: "F", G: "G", A: "A", B: "B" };
const accidentalValue: Record<MusicalNote["accidental"], number> = { natural: 0, sharp: 1, flat: -1 };
function escapeXml(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&apos;"); }
function durationType(beats: number): { duration: number; type: string; dots: number } { if (beats >= 4) return { duration: 16, type: "whole", dots: 0 }; if (beats >= 2) return { duration: 8, type: "half", dots: 0 }; if (beats >= 1.5) return { duration: 12, type: "quarter", dots: 1 }; if (beats >= 1) return { duration: 4, type: "quarter", dots: 0 }; if (beats >= 0.75) return { duration: 6, type: "eighth", dots: 1 }; if (beats >= 0.5) return { duration: 2, type: "eighth", dots: 0 }; if (beats >= 0.25) return { duration: 1, type: "16th", dots: 0 }; return { duration: 1, type: "32nd", dots: 0 }; }
function renderNote(note: MusicalNote, chord = false): string { const shape = durationType(effectiveNoteDurationBeats(note)); const alter = accidentalValue[note.accidental]; const voice = Math.max(1, Math.floor(note.voice ?? 1)); const tuplet = note.tuplet && note.tuplet.actual > 0 && note.tuplet.normal > 0 ? `<time-modification><actual-notes>${note.tuplet.actual}</actual-notes><normal-notes>${note.tuplet.normal}</normal-notes></time-modification>` : ""; return `<note>${chord ? "<chord/>" : ""}<pitch><step>${pitchStep[note.pitch]}</step>${alter ? `<alter>${alter}</alter>` : ""}<octave>${note.octave}</octave></pitch><duration>${shape.duration}</duration><voice>${voice}</voice><type>${shape.type}</type>${"<dot>".repeat(shape.dots)}${tuplet}</note>`; }
function renderVoice(notes: MusicalNote[], measureStart: number, divisions: number, voice: number, measureDuration: number): string {
  let cursor = 0;
  let previousStart = -1;
  return notes.sort((a, b) => a.startBeat - b.startBeat || a.octave - b.octave).map((note) => {
    const start = Math.max(0, note.startBeat - measureStart);
    const forwardBeats = Math.max(0, start - cursor);
    const forward = forwardBeats > 0 ? `<forward><duration>${Math.round(forwardBeats * divisions)}</duration></forward>` : "";
    cursor = Math.max(cursor, start + effectiveNoteDurationBeats(note));
    const chord = previousStart === note.startBeat;
    previousStart = note.startBeat;
    return `${chord ? "" : forward}${renderNote({ ...note, voice }, chord)}`;
  }).join("") || `<note><rest/><duration>${measureDuration}</duration><voice>${voice}</voice><type>whole</type></note>`;
}
export function exportMusicXml(project: MusicProjectState, title = "VARYNTH Composition"): string {
  const divisions = 4; const beatsPerMeasure = project.timeSignature.numerator * (4 / project.timeSignature.denominator); const measureDuration = beatsPerMeasure * divisions; const notes = flattenMusicNotes(project).sort((a, b) => a.startBeat - b.startBeat || (a.voice ?? 1) - (b.voice ?? 1) || a.octave - b.octave); const maxBeat = Math.max(0, ...notes.map((note) => note.startBeat + effectiveNoteDurationBeats(note))); const measureCount = Math.max(1, Math.ceil(Math.max(maxBeat, beatsPerMeasure) / beatsPerMeasure)); const keyFifths = project.key.scale === "minor" ? -3 : 0; const measures = Array.from({ length: measureCount }, (_, measureIndex) => { const start = measureIndex * beatsPerMeasure; const end = start + beatsPerMeasure; const inMeasure = notes.filter((note) => note.startBeat >= start && note.startBeat < end); const voices = [...new Set(inMeasure.map((note) => Math.max(1, Math.floor(note.voice ?? 1))))].sort((a, b) => a - b); const body = (voices.length ? voices : [1]).map((voice, voiceIndex) => { const voiceNotes = inMeasure.filter((note) => Math.max(1, Math.floor(note.voice ?? 1)) === voice); const content = renderVoice(voiceNotes, start, divisions, voice, measureDuration); return `${voiceIndex > 0 ? `<backup><duration>${measureDuration}</duration></backup>` : ""}${content}`; }).join(""); const attributes = measureIndex === 0 ? `<attributes><divisions>${divisions}</divisions><key><fifths>${keyFifths}</fifths><mode>${project.key.scale === "minor" ? "minor" : "major"}</mode></key><time><beats>${project.timeSignature.numerator}</beats><beat-type>${project.timeSignature.denominator}</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>` : ""; const direction = measureIndex === 0 ? `<direction placement="above"><direction-type><metronome><beat-unit>quarter</beat-unit><per-minute>${project.tempoMap[0]?.bpm || 120}</per-minute></metronome></direction-type><sound tempo="${project.tempoMap[0]?.bpm || 120}"/></direction>` : ""; return `<measure number="${measureIndex + 1}">${attributes}${direction}${body}</measure>`; }).join(""); return `<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>${escapeXml(title)}</work-title></work><part-list><score-part id="P1"><part-name>VARYNTH</part-name></score-part></part-list><part id="P1">${measures}</part></score-partwise>`;
}
