import { beatsToSeconds, chordToNotes, constrainNotesToScale, defaultMusicProject, durationToBeats, effectiveNoteDurationBeats, flattenMusicNotes, humanizeNotes, midiToFrequency, midiToPitch, pitchToFrequency, pitchToMidi, quantizeBeat, quantizeNotes, tempoMapBeatsToSeconds, tempoMapSecondsToBeats, transposeNote, upsertTempoPoint, beatsPerMeasure, musicLoopPositionAtMs, setMusicLoopBars } from "./music-domain";

function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
assert(pitchToMidi("A", 4) === 69, "A4 deve ser MIDI 69");
assert(effectiveNoteDurationBeats({ durationBeats: 1, tuplet: { actual: 3, normal: 2 } }) === 2 / 3, "Tuplet deve reduzir a duração efetiva");
assert(Math.abs(pitchToFrequency("A", 4) - 440) < 0.0001, "A4 deve ser 440Hz");
assert(midiToFrequency(60) > 261 && midiToFrequency(60) < 262, "C4 deve ter frequência correta");
assert(midiToPitch(60).pitch === "C" && midiToPitch(60).octave === 4, "C4 deve retornar corretamente");
assert(beatsToSeconds(4, 60) === 4, "Tempo deve converter beats para segundos");
assert(durationToBeats("quarter") === 1 && durationToBeats("half", true) === 3, "Durações musicais devem ser reais");
assert(quantizeBeat(1.12, 4) === 1, "Quantização de semínima deve funcionar");
const transposed = transposeNote({ id: "n", pitch: "C", accidental: "natural", octave: 4, startBeat: 0, durationBeats: 1, velocity: 96 }, 12);
assert(transposed.pitch === "C" && transposed.octave === 5, "Transposição deve preservar o modelo musical");
const constrained = constrainNotesToScale([{ id: "chromatic", pitch: "C", accidental: "sharp", octave: 4, startBeat: 0, durationBeats: 1, velocity: 96 }], pitchToMidi("C", 0), "major")[0];
assert(pitchToMidi(constrained.pitch, constrained.octave, constrained.accidental) === pitchToMidi("C", 4), "Correção de escala deve escolher a nota diatônica mais próxima");
assert(defaultMusicProject().tempoMap[0].bpm === 120, "Projeto musical deve ter tempo padrão");
const baseNote = { id: "q", pitch: "C" as const, accidental: "natural" as const, octave: 4, startBeat: 1.13, durationBeats: 1, velocity: 96 };
assert(quantizeNotes([baseNote], 4)[0].startBeat === 1 && quantizeNotes([baseNote], 4)[0].originalStartBeat === 1.13, "Quantização deve preservar origem");
assert(humanizeNotes([baseNote], 0.02, 4, 7)[0].originalVelocity === 96, "Humanização deve preservar velocity original");
assert(chordToNotes({ id: "c", root: "C", accidental: "natural", octave: 4, quality: "major", startBeat: 0, durationBeats: 4 }).length === 3, "Acorde maior deve materializar 3 notas");
const extendedChord = chordToNotes({ id: "c9", root: "C", accidental: "natural", octave: 4, quality: "major", extensions: [9], inversion: 1, startBeat: 0, durationBeats: 4 });
assert(extendedChord.length === 4 && extendedChord[0].pitch === "E" && extendedChord.at(-1)?.octave === 5, "Extensão e inversão devem alterar as notas do acorde");
assert(extendedChord.every((note) => note.chordId === "c9"), "Notas materializadas devem manter a relação com o acorde");
const spreadChord = chordToNotes({ id: "spread", root: "C", accidental: "natural", octave: 4, quality: "major", voicing: "spread", startBeat: 0, durationBeats: 1 });
assert(spreadChord[1].octave > spreadChord[0].octave, "Voicing spread deve abrir vozes alternadas");
assert(tempoMapBeatsToSeconds(6, [{ beat: 0, bpm: 60 }, { beat: 4, bpm: 120 }]) === 5, "Tempo map deve calcular mudanças de BPM");
assert(Math.abs(tempoMapSecondsToBeats(5, [{ beat: 0, bpm: 60 }, { beat: 4, bpm: 120 }]) - 6) < 0.001, "Tempo map inverso deve ser consistente");
assert(upsertTempoPoint([{ beat: 0, bpm: 120 }], { beat: 8, bpm: 90 })[1].bpm === 90, "Tempo point deve ser ordenado");
const loopProject = setMusicLoopBars(defaultMusicProject(), 3, 7, true);
assert(beatsPerMeasure({ numerator: 6, denominator: 8 }) === 3, "Compasso 6/8 deve equivaler a três beats de semínima");
assert(loopProject.loopRegion?.startBeat === 8 && loopProject.loopRegion.endBeat === 24, "Região musical deve ser armazenada em beats absolutos");
const tempoLoop = { enabled: true, startBeat: 8, endBeat: 24 };
assert(musicLoopPositionAtMs(19999, tempoLoop, [{ beat: 0, bpm: 120 }, { beat: 8, bpm: 60 }]) === null, "Loop não deve disparar antes do compasso final");
assert(musicLoopPositionAtMs(20000, tempoLoop, [{ beat: 0, bpm: 120 }, { beat: 8, bpm: 60 }]) === 4000, "Loop musical deve voltar ao início respeitando o tempo map");
const offsetMusic = { ...defaultMusicProject(), tempoMap: [{ beat: 0, bpm: 120 }, { beat: 4, bpm: 60 }], clips: [{ id: "offset", trackId: "midi", name: "Offset", timelineStartMs: 3000, startBeat: 2, endBeat: 6, transposeSemitones: 0, notes: [{ ...baseNote, startBeat: 0 }] }] };
assert(flattenMusicNotes(offsetMusic)[0].startBeat === 7, "Music Clip deve converter timelineStartMs pelo tempo map completo");
const transposingMusic = { ...offsetMusic, clips: [{ ...offsetMusic.clips[0], transposeSemitones: 2 }] };
assert(flattenMusicNotes(transposingMusic)[0].pitch === "D" && flattenMusicNotes(transposingMusic)[0].octave === 4, "Transposição do Music Clip deve alcançar playback e edição flattened");
assert(Math.abs(pitchToFrequency("A", 4, "natural", 442) - 442) < 0.0001, "Afinação de concerto deve redefinir a frequência de A4");
console.log("Music domain tests passed: pitch, tuning, tempo, durations, quantization, transpose and serialization defaults.");
