export type ProceduralAmbienceKind = "rain" | "wind" | "forest";
export interface ProceduralAmbienceOptions { kind: ProceduralAmbienceKind; durationSeconds: number; intensity: number; density: number; distance: number; seed?: number; sampleRate?: number; }

function writeAscii(view: DataView, offset: number, value: string) { for (let index = 0; index < value.length; index++) view.setUint8(offset + index, value.charCodeAt(index)); }
function seededNoise(seed: number) { let state = seed >>> 0; return () => { state = (1664525 * state + 1013904223) >>> 0; return (state / 4294967296) * 2 - 1; }; }
function wav(samples: Float32Array, sampleRate: number, channels: number): ArrayBuffer { const bytes = 44 + samples.length * 2; const view = new DataView(new ArrayBuffer(bytes)); writeAscii(view, 0, "RIFF"); view.setUint32(4, bytes - 8, true); writeAscii(view, 8, "WAVEfmt "); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, channels, true); view.setUint32(24, sampleRate, true); view.setUint32(28, sampleRate * channels * 2, true); view.setUint16(32, channels * 2, true); view.setUint16(34, 16, true); writeAscii(view, 36, "data"); view.setUint32(40, bytes - 44, true); for (let index = 0; index < samples.length; index++) view.setInt16(44 + index * 2, Math.round(Math.max(-1, Math.min(1, samples[index])) * 32767), true); return view.buffer; }

export function generateProceduralAmbience(options: ProceduralAmbienceOptions): { data: ArrayBuffer; durationSeconds: number; sampleRate: number; channels: 2; seed: number } {
  const durationSeconds = Number(options.durationSeconds); const intensity = Number(options.intensity); const density = Number(options.density); const distance = Number(options.distance); const sampleRate = options.sampleRate || 48000; const channels = 2;
  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0 || durationSeconds > 300) throw new Error("A duração do ambience deve estar entre 0 e 300 segundos.");
  if (![intensity, density, distance].every((value) => Number.isFinite(value) && value >= 0 && value <= 1)) throw new Error("Intensidade, densidade e distância devem estar entre 0 e 1.");
  const seed = Number.isFinite(options.seed) ? Math.trunc(options.seed as number) : options.kind.length * 997 + Math.round(intensity * 100) + Math.round(density * 31); const frames = Math.max(1, Math.round(durationSeconds * sampleRate)); const samples = new Float32Array(frames * channels); const random = seededNoise(seed); let low = 0; let gust = 0; const gain = 0.08 + intensity * 0.2;
  for (let frame = 0; frame < frames; frame++) { const t = frame / sampleRate; const white = random(); low = low * 0.995 + white * 0.005; gust = gust * 0.9995 + random() * 0.0005; let value = options.kind === "rain" ? (white * 0.65 + low * 2.2) * (0.35 + density * 0.65) : options.kind === "wind" ? (low * 2.5 + Math.sin(t * (0.12 + density * 0.5)) * 0.35 + gust * 3) * (0.4 + density * 0.6) : (low * 1.4 + Math.sin(t * 0.7) * 0.12 + white * density * 0.2); if (options.kind === "forest" && Math.abs(random()) > 1 - density * 0.0008) value += random() * 0.8; const fade = Math.min(1, t * 8, (durationSeconds - t) * 8); value *= gain * Math.max(0.15, 1 - distance * 0.7) * Math.max(0, fade); samples[frame * 2] = value; samples[frame * 2 + 1] = value * (0.96 + random() * 0.04); }
  return { data: wav(samples, sampleRate, channels), durationSeconds, sampleRate, channels, seed };
}
