import { effectiveNoteDurationBeats, flattenMusicNotes, MusicProjectState } from "./music-domain";

function pdfEscape(value: string): string { return value.replace(/([\\()])/g, "\\$1").replace(/[^\x20-\x7E]/g, "?"); }
function makeText(text: string, x: number, y: number, size = 11): string { return `BT /F1 ${size} Tf ${x} ${y} Td (${pdfEscape(text)}) Tj ET`; }
function makeTupletBracket(y: number, label: string): string { return `q 0.2 w 430 ${y + 5} m 475 ${y + 5} l 475 ${y - 8} m 430 ${y - 8} l S Q ${makeText(label, 480, y - 2, 8)}`; }

export function exportScorePdf(project: MusicProjectState, title = "VARYNTH Score"): Uint8Array {
  const notes = flattenMusicNotes(project).sort((a, b) => a.startBeat - b.startBeat); const lines = [title, `Tempo: ${project.tempoMap[0]?.bpm || 120} BPM`, `Key: ${project.key.tonic} ${project.key.scale}`, `Time: ${project.timeSignature.numerator}/${project.timeSignature.denominator}`, "", ...notes.slice(0, 28).map((note, index) => `${index + 1}. ${note.pitch}${note.accidental === "sharp" ? "#" : note.accidental === "flat" ? "b" : ""}${note.octave}  beat ${note.startBeat}  duration ${effectiveNoteDurationBeats(note)}${note.tuplet ? `  tuplet ${note.tuplet.actual}:${note.tuplet.normal}` : ""}  velocity ${note.velocity}`)];
  const tuplets = notes.slice(0, 28).flatMap((note, index) => note.tuplet ? [makeTupletBracket(760 - (index + 5) * 22, `${note.tuplet.actual}:${note.tuplet.normal}`)] : []); const content = ["q", ...lines.map((line, index) => makeText(line, 54, 760 - index * 22, index === 0 ? 18 : 10)), ...tuplets, "Q"].join("\\n"); const objects = [`<< /Type /Catalog /Pages 2 0 R >>`, `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`, `<< /Length ${content.length} >>\nstream\n${content}\nendstream`]; let pdf = "%PDF-1.4\n"; const offsets = [0]; objects.forEach((object, index) => { offsets.push(pdf.length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(pdf);
}
