export type DocCategory =
  | "architecture"
  | "athena"
  | "modules"
  | "adr"
  | "history"
  | "development"
  | "handbook";

export type ComponentStatus =
  | "IMPLEMENTED"
  | "PARTIALLY_IMPLEMENTED"
  | "PLANNED"
  | "EXPERIMENTAL"
  | "DEPRECATED";

export interface TechnicalDocItem {
  id: string;
  slug: string;
  title: string;
  category: DocCategory;
  categoryLabel: string;
  icon: string;
  status: ComponentStatus;
  lastVerified: string;
  summary: string;
  sourceFilePath: string;
  content: string;
  tags: string[];
  relatedADRs?: string[];
  relatedComponents?: string[];
}

export interface ADRItem {
  id: string;
  number: string;
  title: string;
  status: "Accepted" | "Superseded" | "Deprecated";
  date: string;
  context: string;
  decision: string;
  rationale: string;
  alternatives: string[];
  consequences: {
    gains: string[];
    tradeoffs: string[];
  };
}

export interface LessonLearnedItem {
  id: string;
  number: string;
  title: string;
  problem: string;
  observation: string;
  decision: string;
  result: string;
  linkedRegressionTest?: string;
}

export interface HandbookChapter {
  number: string;
  title: string;
  summary: string;
  content: string;
}

// ---------------------------------------------------------------------------
// SOURCE OF TRUTH: Structured data mapped directly from /docs
// ---------------------------------------------------------------------------

export const ADR_LIST: ADRItem[] = [
  {
    id: "ADR-001",
    number: "ADR-001",
    title: "Soberania Tecnológica Local-First & Independência de APIs Comerciais",
    status: "Accepted",
    date: "2026-08-29",
    context: "Trabalho intelectual de alta densidade envolve teses inéditas e dados confidenciais protegidos por sigilo. O envio de dados para APIs comerciais (OpenAI, Claude, Gemini) cria vulnerabilidades e custos contínuos.",
    decision: "A Athena e o VARYNTH OS operam exclusivamente Local-First, sem chaves de API externas. Inferência neural é opcional via Ollama local (127.0.0.1:11434) com baseline determinístico de 0 ms.",
    rationale: "Garante privacidade absoluta, funcionamento offline e custo zero recorrente com tokens.",
    alternatives: ["Proxy corporativo para OpenAI/Claude", "SDK de IA em nuvem comercial"],
    consequences: {
      gains: ["Privacidade total", "Auditabilidade determinística", "Latência de 0 ms no baseline"],
      tradeoffs: ["Dependência da capacidade computacional da GPU/CPU local para inferência neural densa"],
    },
  },
  {
    id: "ADR-002",
    number: "ADR-002",
    title: "Retenção de 10 Dias na Lixeira, Desfazer (Undo) & Alex Principle",
    status: "Accepted",
    date: "2026-08-29",
    context: "Exclusões acidentais ou comandos imperativos ambíguos (ex: 'apague isso') poderiam destruir semanas de pesquisa.",
    decision: "Nenhuma exclusão é permanente no ato. Todos os recursos entram em quarentena de 10 dias no módulo Trash com suporte a Undo. Alvos ambíguos ativam bloqueio Fail-Closed (Alex Principle).",
    rationale: "Impede perda irreversível de dados por erro humano ou interpretação equivocada de linguagem natural.",
    alternatives: ["Exclusão física direta com diálogo de confirmação simples", "Soft delete permanente sem quarentena"],
    consequences: {
      gains: ["Segurança total contra perda de dados", "Reversibilidade imediata"],
      tradeoffs: ["Exige rotina de purga periódica para itens com mais de 10 dias"],
    },
  },
  {
    id: "ADR-003",
    number: "ADR-003",
    title: "Roteamento em Três Vias de Interação (Fast, Cognitive & Operational)",
    status: "Accepted",
    date: "2026-08-29",
    context: "Tratar todas as mensagens em um funil monolítico causava despejo de banco em conversas sociais ('como você está?') e evasão em pedidos compostos de ideação.",
    decision: "Separar a execução em 3 vias estritas: CONVERSATION (Fast Path), COGNITIVE_REQUEST (Cognitive Path) e OPERATIONAL_REQUEST (Action Path).",
    rationale: "Capacidade não implica intenção. Diálogos sociais devem ser empáticos e leves; pedidos cognitivos devem ser densos e diretos.",
    alternatives: ["Funil único com prompt de sistema gigante", "Agente puramente reativo"],
    consequences: {
      gains: ["Eliminação do despejo de dados em conversas casuais", "Composição flexível de intenções cognitivas"],
      tradeoffs: ["Exige classificador semântico em camadas no ConversationManager"],
    },
  },
  {
    id: "ADR-004",
    number: "ADR-004",
    title: "Política Anti-Fallback Genérico, Resposta Direta & Validação de Completude",
    status: "Accepted",
    date: "2026-08-29",
    context: "Respostas como 'Entendi perfeitamente... como gostaria de encaminhar essa reflexão?' fingiam inteligência sem entregar o que o usuário pediu.",
    decision: "Extirpação completa de frases evasivas, adoção do Princípio de Resposta Direta e checagem prévia pelo ResponseCompletenessValidator.",
    rationale: "Athena deve demonstrar compreensão através de respostas substanciais imediatas e admitir incerteza honestamente se a confiança for baixa.",
    alternatives: ["Manter fallbacks genéricos como segurança de último caso"],
    consequences: {
      gains: ["Respostas ricas e proativas", "Fim da frustração com evasões"],
      tradeoffs: ["Exige validação semântica antes de liberar a resposta final"],
    },
  },
  {
    id: "ADR-005",
    number: "ADR-005",
    title: "Conselho Determinístico de 7 Especialistas Cognitivos",
    status: "Accepted",
    date: "2026-08-29",
    context: "Assistentes monolíticos misturam domínios de forma inconsistente, sem validação crítica de riscos.",
    decision: "Criar um Conselho de 7 agentes com competências formais: Justitia, Logos, Sophia, Musa, Strategos, Mnemosyne e Critias.",
    rationale: "Especialização de domínio e revisão crítica obrigatória por Critias garantem rigor acadêmico e dogmático.",
    alternatives: ["Persona única adaptativa via prompts longos"],
    consequences: {
      gains: ["Deliberação dialética e pareceres balanceados", "Previsibilidade metodológica"],
      tradeoffs: ["Maior quantidade de arquivos e interfaces de agentes para manter"],
    },
  },
  {
    id: "ADR-006",
    number: "ADR-006",
    title: "Base Epistêmica Embutida Offline para Filosofia, Direito e Ciência",
    status: "Accepted",
    date: "2026-08-29",
    context: "Consultas conceituais fundamentais (Hermenêutica, Teoria dos Jogos, Método Científico, Latim) exigiam respostas imediatas sem depender de IA externa.",
    decision: "Embutir uma base estruturada de conhecimento epistêmico diretamente no código da Athena.",
    rationale: "Garante respostas filosóficas e metodológicas profundas com latência de 0 ms mesmo em modo 100% offline.",
    alternatives: ["Indexação RAG puramente dinâmica em tempo de execução"],
    consequences: {
      gains: ["Velocidade instantânea", "Confiabilidade conceitual inquestionável"],
      tradeoffs: ["Base precisa ser enriquecida manualmente no código-fonte"],
    },
  },
  {
    id: "ADR-008",
    number: "ADR-008",
    title: "Modelo de Autoridade e Matriz de Permissões da Athena (Core Sovereign Rule)",
    status: "Accepted",
    date: "2026-08-29",
    context: "O avanço cognitivo da Athena e futuros studios criativos aumentam o risco de mutações acidentais, destruição de dados ou alterações indevidas no código do sistema.",
    decision: "Centralizar toda autorização no PermissionPolicyEngine. Core Sovereign Rule bloqueia modificação do Core (DENY); deleção permanente é estritamente proibida (DENY); publicações exigem confirmação humana (CONFIRM).",
    rationale: "Capacidade não implica autoridade. A Athena pode se tornar extremamente inteligente sem adquirir autoridade irrestrita.",
    alternatives: ["Permissões isoladas por ferramenta", "Autorização baseada em confiança implícita"],
    consequences: {
      gains: ["Proteção absoluta do Core", "Impossibilidade de destruição acidental de dados", "Tokens anti-replay"],
      tradeoffs: ["Operações de alta criticidade exigem confirmação explícita do usuário"],
    },
  },
  {
    id: "ADR-009",
    number: "ADR-009",
    title: "Modelo Universal de Artefatos, VersionManager e AssetManager (File != Artifact)",
    status: "Accepted",
    date: "2026-08-29",
    context: "Tratar documentos, vídeos, código, jogos e áudios como estruturas desconectadas causaria fragmentação de persistência e perda de rastreabilidade epistêmica.",
    decision: "Formalizar o Universal Artifact System separando Project, Artifact, AssetFile, Version e Job. VersionManager adota Alex Principle; AssetManager gerencia OPFS/IndexedDB Blob sem Base64 em LocalStorage.",
    rationale: "Permite que todos os tipos de criação compartilhem o mesmo ciclo de vida, permissões, auditoria e proveniência.",
    alternatives: ["Sistemas isolados por estúdio", "Persistência em arquivos planos sem metadados"],
    consequences: {
      gains: ["Arquitetura unificada para futuros studios", "Consistência de assets obrigatórios", "Transparência de capacidade"],
      tradeoffs: ["Exige sincronização entre repositório conceitual de artefatos e armazenamento de assets"],
    },
  },
  {
    id: "ADR-010",
    number: "ADR-010",
    title: "Job Runtime Universal, Checkpoints e Modelo de Isolamento de Sandbox",
    status: "Accepted",
    date: "2026-08-29",
    context: "Processos de longa duração necessitam de State Machine transparente, checkpoints e recuperação após reinicialização. Código e scripts de IA exigem contenção rigorosa.",
    decision: "Centralizar execuções em JobManager (com detecção de interrupção e retries) e isolamento em SandboxRuntime (com Core Sovereign Guard e barreira de rede estrita).",
    rationale: "Garante estabilidade operacional sem risco de travamento de estado e impede que scripts arbitrários afetem o Core do VARYNTH.",
    alternatives: ["Promises não persistidas em memória", "Execução direta no runtime principal do browser"],
    consequences: {
      gains: ["Tolerância a falhas", "Visibilidade do ciclo de execução", "Proteção inviolável do Core"],
      tradeoffs: ["Necessidade de validação extra antes de promover outputs da sandbox"],
    },
  },
  {
    id: "ADR-011",
    number: "ADR-011",
    title: "Ordem Canônica de Implementação dos Studios Criativos",
    status: "Accepted",
    date: "2026-08-29",
    context: "Construir estúdios pesados (vídeo e jogos) antes de editores estruturados e pipelines de assets geraria duplicação e alto retrabalho.",
    decision: "Fixar a ordem canônica: Document Studio -> Web Studio -> Image Studio -> Audio Studio -> Video Studio -> Game Studio. Cada estúdio valida uma camada específica da Creation Foundation.",
    rationale: "Progressão de baixo custo computacional para mídia densa, garantindo reaproveitamento total da pilha de criação.",
    alternatives: ["Desenvolvimento simultâneo de todos os estúdios", "Iniciar diretamente pelo Video Studio"],
    consequences: {
      gains: ["Reutilização total de infraestrutura", "Zero retrabalho", "Previsibilidade do roadmap"],
      tradeoffs: ["Estúdios audiovisuais e de jogos aguardam a maturação dos estúdios fundamentais"],
    },
  },
  {
    id: "ADR-012",
    number: "ADR-012",
    title: "Document Studio como Primeira Implementação de Estúdio",
    status: "Accepted",
    date: "2026-08-29",
    context: "Validar a Creation Foundation em um estúdio leve e determinístico antes de avançar para estúdios audiovisuais pesados.",
    decision: "Construir o Document Studio como primeiro estúdio oficial, estabelecendo o padrão StudioShell, outline hierárquico, sugestões da Athena e exportação multiplataforma.",
    rationale: "Permite consolidar artefatos, versionamento, persistência e IA com máxima fidelidade e baixo consumo de recursos.",
    alternatives: ["Iniciar pelo Web Studio", "Criar um editor de texto genérico sem modelo Artifact"],
    consequences: {
      gains: ["Validação integral da Creation Foundation", "Componentes reutilizáveis para futuros estúdios", "Geração de roteiros para o Video Studio"],
      tradeoffs: ["Foco inicial no padrão estruturado Markdown"],
    },
  },
  {
    id: "ADR-013",
    number: "ADR-013",
    title: "Web Studio Execution Model e Prevenção de Falso Sucesso",
    status: "Accepted",
    date: "2026-08-29",
    context: "Execuções de compilação web e builds de scripts arbitrários exigem isolamento formal e proteção contra falso sucesso.",
    decision: "Executar builds via JobManager em SandboxRuntime com watchdog preemptivo, promovendo saídas para o AssetManager apenas quando válidas.",
    rationale: "Garante integridade e evita que websites falhos sejam marcados indevidamente como ativos.",
    alternatives: ["Build síncrono no thread principal", "Armazenamento direto sem validação de asset"],
    consequences: {
      gains: ["Execução assíncrona tolerante a falhas", "Interrupção de loops infinitos", "Zero falso sucesso"],
      tradeoffs: ["Necessidade de etapa formal de promoção de assets"],
    },
  },
  {
    id: "ADR-014",
    number: "ADR-014",
    title: "Web Preview Isolation Boundary e Canal de Mensagens Autenticado",
    status: "Accepted",
    date: "2026-08-29",
    context: "Renderizar código web não confiável no navegador sem comprometer o Core do VARYNTH.",
    decision: "Isolar o preview em iframe com sandbox='allow-scripts' e autenticar mensagens com WebPreviewEnvelope, token de sessão criptográfico e rate limiting.",
    rationale: "Impede acesso a parent window, cookies, storage e protege contra flood de mensagens mesmo em origens opacas.",
    alternatives: ["Iframe sem restrições", "Comunicação livre via postMessage baseada em origin"],
    consequences: {
      gains: ["Isolamento rigoroso do Core", "Proteção contra flood", "Comunicação determinística"],
      tradeoffs: ["Necessidade de script cliente injetado no preview"],
    },
  },
  {
    id: "ADR-015",
    number: "ADR-015",
    title: "Modelo de Edição Não-Destrutiva de Imagens e Imutabilidade de Source Assets",
    status: "Accepted",
    date: "2026-08-29",
    context: "A edição visual não pode sobrescrever o asset original importado sob o Princípio Alex.",
    decision: "Manter o source asset como imutável e expressar transformações no ImageDocumentState, gerando Derived Assets no render.",
    rationale: "Permite reversibilidade absoluta, histórico de versões íntegro e compartilhamento seguro do asset original.",
    alternatives: ["Sobrescrita direta do arquivo no disco", "Achatamento síncrono da imagem"],
    consequences: {
      gains: ["Preservação perpétua da fonte", "Rollback não-destrutivo", "Flexibilidade de reedição"],
      tradeoffs: ["Composição sob demanda na etapa de exportação"],
    },
  },
  {
    id: "ADR-016",
    number: "ADR-016",
    title: "Arquitetura de Camadas de Imagem e Pipeline de Renderização Local",
    status: "Accepted",
    date: "2026-08-29",
    context: "Necessidade de manipular camadas compostas com segurança de memória e rastreabilidade local.",
    decision: "Implementar ImageRenderEngine determinístico com suporte a camadas, validação de ciclos em grupos, limites de canvas e formatos raster.",
    rationale: "Garante alta performance, prevenção de crash por memória e operação 100% Local-First.",
    alternatives: ["Serviço em nuvem de renderização", "Editor vetorial complexo"],
    consequences: {
      gains: ["Processamento local rápido", "Proteção contra exaustão de memória", "Rastreabilidade via JobManager"],
      tradeoffs: ["Exportação vetorial SVG postergada"],
    },
  },
  {
    id: "ADR-017",
    number: "ADR-017",
    title: "Modelo de Edição Não-Destrutiva de Áudio e Linha do Tempo",
    status: "Accepted",
    date: "2026-08-29",
    context: "A edição de áudio não pode sobrescrever o arquivo original nem destruir gravações brutas sob o Princípio Alex.",
    decision: "Manter o source asset de áudio como imutável e expressar cortes (trim/split) e ganhos no AudioDocumentState com Undo/Redo de sessão.",
    rationale: "Garante reversibilidade temporal, histórico sem duplicações e integridade de áudios compartilhados.",
    alternatives: ["Corte físico destrutivo no disco", "Gravação em fita linear única"],
    consequences: {
      gains: ["Preservação total dos áudios originais", "Clips reutilizáveis com múltiplos recortes", "Rollback não-destrutivo"],
      tradeoffs: ["Mixagem dinâmica necessária no playback e exportação"],
    },
  },
  {
    id: "ADR-018",
    number: "ADR-018",
    title: "Arquitetura de Motor Multipistas e Pipeline de Renderização de Áudio",
    status: "Accepted",
    date: "2026-08-29",
    context: "Processar áudio multipistas no navegador com segurança dinâmica de memória RAM e codificação WAV PCM 16-bit real.",
    decision: "Implementar AudioRenderEngine com estimativa dinâmica de memória Float32, semântica formal de Mute/Solo e exportação PCM 16-bit.",
    rationale: "Evita travamentos de memória, assegura consistência entre playback e render, e gera arquivos de áudio interoperáveis.",
    alternatives: ["Dependência de APIs de áudio na nuvem", "Falso encoder MP3 com renomeação de extensão"],
    consequences: {
      gains: ["Operação 100% Local-First", "Proteção estrita contra exaustão de memória", "Formato WAV canônico"],
      tradeoffs: ["Encoders MP3/OGG indisponíveis retornam CAPABILITY_UNAVAILABLE"],
    },
  },
  {
    id: "ADR-019",
    number: "ADR-019",
    title: "Núcleo Temporal Compartilhado (TemporalCore) e Modelo Multipistas",
    status: "Accepted",
    date: "2026-08-29",
    context: "Unificar a base de cálculo temporal e conversão de frame rates racionais entre Audio Studio e Video Studio sem drift acumulado.",
    decision: "Extrair o TemporalCore com suporte a taxas racionais (23.976, 29.97, 59.94fps), master timeline clock em milissegundos e funções canônicas de conversão.",
    rationale: "Garante sincronização matemática exata entre áudio, vídeo, legendas e marcadores mantendo zero regressões no Audio Studio.",
    alternatives: ["Fórmulas ad-hoc de ponto flutuante espalhadas pela UI", "Motores de tempo duplicados e incompatíveis"],
    consequences: {
      gains: ["Sincronização rigorosa sem drift", "Snapping magnético unificado", "Preservação integral do Audio Studio"],
      tradeoffs: ["Necessidade de utilizar funções utilitárias centralizadas para conversão"],
    },
  },
  {
    id: "ADR-020",
    number: "ADR-020",
    title: "Edição Não-Destrutiva de Vídeo e Arquitetura de Cenas Semânticas",
    status: "Accepted",
    date: "2026-08-29",
    context: "A edição e montagem de vídeos não pode destruir arquivos de mídia brutos nem duplicar fontes no disco sob o Princípio Alex.",
    decision: "Manter source assets imutáveis e expressar cuts, scenes, transforms, keyframes e legendas no VideoDocumentState com histórico de Undo/Redo desacoplado do VersionManager.",
    rationale: "Permite navegação por cenas semânticas, visualização em Storyboard e reversibilidade total sem inflar versões.",
    alternatives: ["Corte e concatenação destrutiva de arquivos", "Cenas como fontes de tempo concorrentes"],
    consequences: {
      gains: ["Imutabilidade dos originais", "Navegação em Storyboard", "Rollback Alex restaurando como vNext"],
      tradeoffs: ["Composição dinâmica necessária durante preview e render"],
    },
  },
  {
    id: "ADR-021",
    number: "ADR-021",
    title: "Preview de Vídeo e Pipeline Determinístico de Renderização Offline",
    status: "Accepted",
    date: "2026-08-29",
    context: "Processar e compor vídeo localmente no navegador com segurança estrita de memória de trabalho e exportação de alta fidelidade.",
    decision: "Implementar VideoRenderEngine com estimativa conservadora de working-set (teto de 128MB), composição incremental frame a frame e verificação honesta de capacidades de encoder/muxer.",
    rationale: "Evita esgotamento de memória, previne falso sucesso e gera arquivos derivados reais rastreados no JobManager.",
    alternatives: ["Renderização em servidores cloud comerciais", "Decodificação simultânea de todos os frames na memória RAM"],
    consequences: {
      gains: ["Operação 100% Local-First", "Proteção contra exaustão de RAM", "Transparência total nas capacidades reais"],
      tradeoffs: ["Resolução 4K é desabilitada em runtimes com memória insuficiente"],
    },
  },
  {
    id: "ADR-022",
    number: "ADR-022",
    title: "Modelo de Artefato de Jogo Desacoplado de Engine e Arquitetura Entidade-Componente",
    status: "Accepted",
    date: "2026-08-29",
    context: "Representar jogos declarativamente sem acoplamento a engines monolíticas proprietárias, permitindo manipulação inteligente pela Athena.",
    decision: "Estruturar o GameDocumentState sobre arquitetura composicional Entidade-Componente (ECS), com prevenção de ciclos transitivos na hierarquia e imutabilidade de source assets.",
    rationale: "Garante portabilidade, serialização limpa e integridade estrutural sob o Princípio Alex.",
    alternatives: ["Acoplamento direto com Unity/Godot/Phaser", "Classes rígidas para cada objeto do jogo"],
    consequences: {
      gains: ["Portabilidade universal", "Orquestração segura pela Athena", "Hierarquia acíclica rigorosa"],
      tradeoffs: ["Física 3D pesada fora do escopo da V1"],
    },
  },
  {
    id: "ADR-023",
    number: "ADR-023",
    title: "Motor Declarativo de Regras (Rules Before Code) e Play Mode em Sandbox",
    status: "Accepted",
    date: "2026-08-29",
    context: "Permitir que a Athena crie mecânicas ricas sem gerar scripts arbitrários vulneráveis a loops infinitos, isolando a execução de testes.",
    decision: "Implementar GameRulesEngine com proteção de orçamento de execução (RULE_EXECUTION_BUDGET_EXCEEDED), fila de eventos determinística, timestep fixo (60Hz), PRNG com seed e isolamento estrito de GameTestSession.",
    rationale: "Elimina congelamento do navegador, previne tempestades de regras (rule storms) e possibilita replay determinístico de bugs.",
    alternatives: ["Geração irrestrita de código JavaScript para tudo", "Mutação direta do estado editável durante playtest"],
    consequences: {
      gains: ["Zero congelamentos de navegador", "Replay determinístico de sessões", "Segurança absoluta no Sandbox"],
      tradeoffs: ["Mecânicas de alta complexidade exigem scripts em Sandbox"],
    },
  },
  {
    id: "ADR-024",
    number: "ADR-024",
    title: "Pipeline de Compilação de Jogos e Descoberta Honesta de Capacidades",
    status: "Accepted",
    date: "2026-08-29",
    context: "Compilar pacotes de jogos através de jobs formais rastreados com reporte transparente de capacidades de exportação.",
    decision: "Executar builds via JobManager com geração de Derived Build Assets HTML5 e descoberta honesta de capacidades (canExport retorna CAPABILITY_UNAVAILABLE para Android/Desktop sem toolchain).",
    rationale: "Garante transparência, evita falsos executáveis e mantém o processo de build 100% Local-First.",
    alternatives: ["Geração de APKs/EXEs simulados sem compilador", "Compilação síncrona no thread de interface"],
    consequences: {
      gains: ["Builds rastreados no JobManager", "Transparência total de capacidades", "Pacotes Web reproduzíveis"],
      tradeoffs: ["Compilação nativa para consoles/mobile fica para fases posteriores"],
    },
  },
  {
    id: "ADR-025",
    number: "ADR-025",
    title: "Grafo Criativo Unificado e Relações Cross-Studio",
    status: "Accepted",
    date: "2026-08-29",
    context: "Os seis Studios corriam o risco de formar silos isolados sem rastreabilidade de dependências e proveniência.",
    decision: "Instituir o CreativeGraphEngine como camada autoritativa indexando relações declaradas em Artifact.relationships, com regras diferenciadas para ciclos em DAGs causais vs referências associativas.",
    rationale: "Unifica os seis estúdios em um ecossistema coerente e compreendido pela Athena sem duplicar armazenamento.",
    alternatives: ["Silos isolados por estúdio", "Grafo monolítico externo desvinculado dos artefatos"],
    consequences: {
      gains: ["Rastreabilidade de proveniência", "Consultas reversas de dependentes", "Validação de DAG acíclico"],
      tradeoffs: ["Necessidade de reindexação ao alterar relações"],
    },
  },
  {
    id: "ADR-026",
    number: "ADR-026",
    title: "Política de Version Pinning e Tolerância a Dependências Desatualizadas",
    status: "Accepted",
    date: "2026-08-29",
    context: "Evoluções em artefatos de origem não devem alterar silenciosamente composições e renders de consumidores existentes.",
    decision: "Adotar version pinning baseado em targetVersionId imutável com detecção de UPDATE_AVAILABLE e atualização transacional com ATOMIC_ROLLBACK.",
    rationale: "Evita mutações acidentais e quebras invisíveis em composições publicadas.",
    alternatives: ["Atualização silenciosa e automática de tudo", "Pinning baseado apenas em números de versão voláteis"],
    consequences: {
      gains: ["Estabilidade determinística", "Rollback atômico em falha", "Diagnóstico preciso de versões"],
      tradeoffs: ["Exigência de revisão manual de atualizações em artefatos publicados"],
    },
  },
  {
    id: "ADR-027",
    number: "ADR-027",
    title: "Reuso Físico de Assets e Segurança de Lixeira Cross-Studio",
    status: "Accepted",
    date: "2026-08-29",
    context: "Compartilhar assets binários (PNG, WAV, MP4) entre múltiplos estúdios protegendo contra deleções indevidas.",
    decision: "Registrar usos físicos em AssetUsageRecord com preservação histórica no Garbage Collection (Princípio Alex) e distinção entre SOURCE_TRASHED e ASSET_MISSING.",
    rationale: "Maximiza economia de armazenamento sem comprometer a integridade de versões passadas.",
    alternatives: ["Cópia física duplicada para cada estúdio consumidor", "Exclusão agressiva de assets não usados na versão ativa"],
    consequences: {
      gains: ["Zero duplicação física", "Proteção de histórico sob o Princípio Alex", "Diagnóstico honesto de integridade"],
      tradeoffs: ["Maior retenção de armazenamento para histórico de versões"],
    },
  },
];

export const LESSONS_LEARNED_LIST: LessonLearnedItem[] = [
  {
    id: "LESSON-001",
    number: "01",
    title: "Capacidade Não Implica Intenção",
    problem: "Ao receber 'Como você está?', a Athena acionava todos os módulos e despejava um briefing completo do banco de dados.",
    observation: "O usuário estava apenas iniciando uma conversa social cotidiana.",
    decision: "Separar a via rápida CONVERSATION (zero leituras) da via COGNITIVE_REQUEST.",
    result: "Respostas sociais empáticas sem sobrecarregar a tela com dados privados.",
    linkedRegressionTest: "ATH-CONV-001",
  },
  {
    id: "LESSON-002",
    number: "02",
    title: "O Perigo da Evasão Disfarçada de Inteligência",
    problem: "Ao receber 'me dê ideias para hoje? que projeto começar?', a Athena respondia 'Entendi perfeitamente... como gostaria de encaminhar essa reflexão?'.",
    observation: "A frase fingia que o assistente compreendeu, mas não entregava nenhuma ideia.",
    decision: "Adotar o Princípio de Resposta Direta (responder primeiro ao pedido) e validar completude com ResponseCompletenessValidator.",
    result: "Proposição proativa de 3 projetos concretos no Labs/Codex/Vault via Musa e Strategos.",
    linkedRegressionTest: "ATH-CONV-002",
  },
  {
    id: "LESSON-003",
    number: "03",
    title: "Fail-Closed em Ações Destrutivas (Alex Principle)",
    problem: "Comandos vagos como 'apague isso' podiam adivinhar o alvo errado e destruir dados acidentalmente.",
    observation: "Adivinhar intenções em mutações destrutivas é inaceitável em ambientes de pesquisa.",
    decision: "Quarentena de 10 dias na Lixeira com Undo e parada obrigatória (Fail-Closed) em alvos ambíguos.",
    result: "Segurança total contra perda de dados acidental.",
    linkedRegressionTest: "ATH-CONV-003",
  },
  {
    id: "LESSON-004",
    number: "04",
    title: "Resolução de Elipses e Continuidade Multi-Turno",
    problem: "Usuário discutia dois projetos e perguntava 'E o segundo?'. O sistema não resolvia o pronome e pedia repetição.",
    observation: "Linguagem natural humana é repleta de anáforas e elipses dependentes do diálogo anterior.",
    decision: "Manter histórico de recentEntities e recentRecommendations no ConversationManager.",
    result: "Compreensão perfeita de 'o segundo', 'por quê?', 'critique essa ideia' e 'compare os dois'.",
    linkedRegressionTest: "ATH-CONV-004 / ATH-CONV-005",
  },
];

export const TECHNICAL_DOCS: TechnicalDocItem[] = [
  // --- ARCHITECTURE ---
  {
    id: "arch-overview",
    slug: "architecture-overview",
    title: "Visão Geral da Macro-Arquitetura",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🏛️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Filosofia central, pilares de soberania Local-First e divisão em 5 camadas do VARYNTH OS.",
    sourceFilePath: "docs/architecture/overview.md",
    tags: ["arquitetura", "local-first", "soberania", "nextjs16", "react19"],
    relatedADRs: ["ADR-001", "ADR-003"],
    content: `O **VARYNTH OS** é um sistema operacional cognitivo soberano, projetado para amplificar a produtividade intelectual, pesquisa acadêmica e gestão estratégica em um ambiente estritamente **Local-First**.\n\n### Pilares:\n1. **Soberania Local-First**: Zero dependência de APIs de nuvem comerciais.\n2. **Arquitetura Cognitiva em 3 Vias**: Fast Path, Cognitive Path e Operational Path.\n3. **Segurança Fail-Closed**: Lixeira de 10 dias com Undo e Alex Principle.\n4. **Módulos Especializados**: Vault, Codex, Research, Chronos, Labs, Forge e People.`,
  },
  {
    id: "arch-system-map",
    slug: "system-map",
    title: "Mapa do Sistema & Topologia",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🗺️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Mapa topológico de subsistemas, conexões de dados e matriz de componentes implementados vs planejados.",
    sourceFilePath: "docs/architecture/system-map.md",
    tags: ["topologia", "grafo", "subsistemas", "componentes"],
    content: `Mapa topológico completo conectando a interface reativa Next.js 16, o Kernel Cognitivo V4 da Athena, a Action Layer e os 9 módulos de armazenamento local.`,
  },
  {
    id: "arch-data-flow",
    slug: "data-flow",
    title: "Fluxo de Dados & Mutações Reativas",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🔄",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Pipeline de mutações seguras, barramento de eventos (AthenaEventBus) e auditoria de autoria.",
    sourceFilePath: "docs/architecture/data-flow.md",
    tags: ["data-flow", "event-bus", "audit", "reatividade"],
    relatedADRs: ["ADR-003"],
    content: `Fluxo reativo de ponta a ponta detalhando como prompts do usuário transitam pelo ConversationManager, ExecutiveController e ToolManager com emissão de eventos assíncronos.`,
  },
  {
    id: "arch-security",
    slug: "security-model",
    title: "Modelo de Segurança & Alex Principle",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🛡️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Diretrizes de proteção contra destruição acidental de dados, protocolo de lixeira e não-repúdio.",
    sourceFilePath: "docs/architecture/security-model.md",
    tags: ["seguranca", "alex-principle", "lixeira", "audit-trail"],
    relatedADRs: ["ADR-002"],
    content: `Detalhamento do Alex Principle: diante de qualquer comando destrutivo com alvo ambíguo, a Athena bloqueia a execução (Fail-Closed) e exige confirmação.`,
  },
  {
    id: "arch-local-first",
    slug: "local-first-sovereignty",
    title: "Arquitetura Local-First & Soberania",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "💾",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Princípios de soberania de dados, ausência de APIs pagas e inferência local adaptativa.",
    sourceFilePath: "docs/architecture/local-first.md",
    tags: ["local-first", "soberania", "ollama", "offline"],
    relatedADRs: ["ADR-001", "ADR-006"],
    content: `Privacidade inegociável, custo zero recorrente e suporte a inferência neural via servidor local Ollama (127.0.0.1:11434).`,
  },
  {
    id: "arch-universal-artifact",
    slug: "universal-artifact-system",
    title: "Universal Artifact System & Criação Digital",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "📦",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Infraestrutura transversal para criação, versionamento e relacionamento de 11 tipos de artefatos digitais.",
    sourceFilePath: "docs/architecture/universal-artifact-system.md",
    tags: ["artefatos", "versionamento", "file-vs-artifact", "proveniencia", "graph"],
    content: `Separação conceitual entre Artifact e Asset Files, versionamento imutável com snapshots e grafos de relacionamento epistêmico.`,
  },
  {
    id: "arch-persistence-matrix",
    slug: "persistence-matrix",
    title: "Matriz de Persistência Soberana (Local-First)",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🗄️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Mapeamento real e auditado das 20 entidades do sistema, fontes da verdade e resiliência a reload.",
    sourceFilePath: "docs/architecture/persistence-matrix.md",
    tags: ["persistencia", "localstorage", "resiliencia", "auditoria"],
    content: `Mapeamento das 20 entidades do ecossistema operando 100% no cliente sem dependência de nuvem.`,
  },
  {
    id: "arch-permission-policy",
    slug: "permission-policy",
    title: "Modelo de Permissões & Políticas de Execução",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🔐",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Permission Policy Engine com políticas ALLOW, CONFIRM, DENY e SANDBOX para operações da Athena.",
    sourceFilePath: "docs/architecture/permission-policy.md",
    tags: ["permissoes", "seguranca", "politicas", "sandbox", "alex-principle"],
    content: `Regras centrais que impedem modificação do Core e isolam protótipos na Sandbox.`,
  },
  {
    id: "arch-job-runtime",
    slug: "job-runtime",
    title: "Job Runtime & Processamento Assíncrono",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "⚡",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Motor de controle de tarefas assíncronas de longa duração com progresso, logs e notificações.",
    sourceFilePath: "docs/architecture/job-runtime.md",
    tags: ["jobs", "runtime", "progresso", "event-bus", "notificacoes"],
    content: `Filas de processamento para renders, builds e exportações massivas conectadas ao Notification Center.`,
  },
  {
    id: "arch-backup-recovery",
    slug: "backup-and-recovery",
    title: "Universal Backup & Recuperação Soberana",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "💾",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Formato .varynth-backup sanitizado e motor atômico de restauração com merge e replace.",
    sourceFilePath: "docs/architecture/backup-and-recovery.md",
    tags: ["backup", "portabilidade", "restauracao", "json", "soberania"],
    content: `Pacote universal exportável com manifesto de integridade e zero vazamento de credenciais.`,
  },
  {
    id: "arch-studio-readiness",
    slug: "studio-readiness",
    title: "VARYNTH Studio Readiness & Futuras Engines",
    category: "architecture",
    categoryLabel: "Arquitetura Global",
    icon: "🎬",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Prontidão arquitetural para acomodar Video Studio, Game Studio, Web Studio e Audio Studio.",
    sourceFilePath: "docs/architecture/studio-readiness.md",
    tags: ["studios", "video-studio", "game-studio", "webassembly", "engines"],
    content: `Infraestrutura unificada e pronta para engines locais sem dependência de APIs proprietárias.`,
  },

  // --- ATHENA COGNITIVE OS ---
  {
    id: "ath-overview",
    slug: "athena-overview",
    title: "Athena: Copilot Cognitivo Soberano",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "🦉",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Visão geral da parceira intelectual do VARYNTH OS e princípios de persona e rigor.",
    sourceFilePath: "docs/athena/overview.md",
    tags: ["athena", "copilot", "cognitivo", "persona"],
    relatedADRs: ["ADR-004", "ADR-005"],
    content: `A Athena é o núcleo de inteligência do VARYNTH OS. Ela integra o Conselho de 7 Especialistas, a Action Layer e uma suíte de regressão de 73 testes.`,
  },
  {
    id: "ath-kernel",
    slug: "cognitive-kernel",
    title: "Kernel Cognitivo V4 & ExecutiveController",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "🧠",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Ciclos de percepção, avaliação orçamentária, roteamento em DAG e agendamento de tarefas.",
    sourceFilePath: "docs/athena/cognitive-kernel.md",
    tags: ["kernel", "perception", "executive-controller", "dag"],
    content: `Orquestração central de requisições com controle orçamentário (FAST, STANDARD, EXHAUSTIVE) e rastreamento de proveniência.`,
  },
  {
    id: "ath-conv-mgr",
    slug: "conversation-manager",
    title: "ConversationManager & Anáforas",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "🗣️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Roteamento em 3 vias, resolução contextual de elipses ('o segundo', 'por quê?') e pilha de entidades.",
    sourceFilePath: "docs/athena/conversation-manager.md",
    tags: ["conversation", "elipses", "anaforas", "intencoes-compostas"],
    relatedADRs: ["ADR-003", "ADR-004"],
    content: `Substituição definitiva de regex por análise semântica em camadas com rastreamento de recentEntities e recentRecommendations.`,
  },
  {
    id: "ath-agents",
    slug: "council-of-agents",
    title: "Conselho de 7 Especialistas Cognitivos",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "👥",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Justitia, Logos, Sophia, Musa, Strategos, Mnemosyne e Critias atuando com deliberação consensual.",
    sourceFilePath: "docs/athena/agents.md",
    tags: ["conselho", "multiagente", "justitia", "critias", "musa"],
    relatedADRs: ["ADR-005"],
    content: `Especialistas formais dedicados a cada domínio: Direito, Ciência, Filosofia, Ideação, Estratégia, Memória e Crítica de Riscos.`,
  },
  {
    id: "ath-tools",
    slug: "action-layer-tools",
    title: "Action Layer & 14 Ferramentas Determinísticas",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "⚙️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Catálogo completo de ferramentas com carimbo de ator, quarentena de 10 dias e Audit Trail.",
    sourceFilePath: "docs/athena/tools.md",
    tags: ["tools", "action-layer", "audit-trail", "mutacao"],
    relatedADRs: ["ADR-002"],
    content: `Execução segura de mutações (tarefas, notas, prazos, lixeira) com garantias de atomicidade e reversibilidade.`,
  },
  {
    id: "ath-safety",
    slug: "safety-and-regressions",
    title: "Segurança, Anti-Evasão & Suíte de Regressão",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "🔒",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Validação de completude, telemetria local de falhas e suíte permanente com 73 testes aprovados (100%).",
    sourceFilePath: "docs/athena/safety.md",
    tags: ["safety", "anti-evasion", "quality-gates", "regression"],
    relatedADRs: ["ADR-004"],
    content: `Qualquer alteração na Athena deve passar por 73 testes históricos cobrindo 15 classes reais de erro antes do deploy.`,
  },
  {
    id: "ath-permissions",
    slug: "athena-permissions-architecture",
    title: "Athena Action & Permission Architecture (Core Sovereign Rule)",
    category: "athena",
    categoryLabel: "Athena Cognitive OS",
    icon: "🛡️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Camada central de autoridade com políticas ALLOW, CONFIRM, DENY, SANDBOX e tokens anti-replay.",
    sourceFilePath: "docs/architecture/athena-action-permission-architecture.md",
    tags: ["permissoes", "autoridade", "core-sovereign-rule", "sandbox", "tokens"],
    relatedADRs: ["ADR-008"],
    content: `Capacidade não implica autoridade. A Athena é proibida de alterar o Core ou expurgar a Lixeira, e publicações exigem validação humana.`,
  },

  // --- MODULES ---
  {
    id: "mod-vault",
    slug: "module-vault",
    title: "Vault: Acervo Universal de Conhecimento",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "📚",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Segundo cérebro para artigos, livros, jurisprudência, links e controle de status de leitura.",
    sourceFilePath: "docs/modules/vault.md",
    tags: ["vault", "biblioteca", "livros", "artigos"],
    content: `Gestão taxonômica de referências bibliográficas com integração ao agente Mnemosyne para recuperação contextual.`,
  },
  {
    id: "mod-codex",
    slug: "module-codex",
    title: "Codex: Argument Arena & Precedentes",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "⚖️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Matriz dialética de controvérsias jurídicas, argumentos pró/contra e teses do STF/STJ.",
    sourceFilePath: "docs/modules/codex.md",
    tags: ["codex", "argument-arena", "direito", "precedentes"],
    content: `Estruturação de debates jurídicos com deliberação entre Justitia (fundamentação) e Critias (riscos de admissibilidade).`,
  },
  {
    id: "mod-research",
    slug: "module-research",
    title: "Research: Evidence Board & Rigor Científico",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "🔬",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Catalogação de evidências científicas com avaliação de força probatória e fontes primárias.",
    sourceFilePath: "docs/modules/research.md",
    tags: ["research", "evidence-board", "ciencia", "metodologia"],
    content: `Validação empírica de alegações científicas coordenada pelo especialista Logos.`,
  },
  {
    id: "mod-chronos",
    slug: "module-chronos",
    title: "Chronos: Motor Temporal & Prazos",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "⏳",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Sincronização de prazos processuais fatais, datas de submissão e marcos de projetos.",
    sourceFilePath: "docs/modules/chronos.md",
    tags: ["chronos", "tempo", "calendario", "prazos"],
    content: `Linha do tempo interativa monitorada pelo estrategista Strategos para prevenção de sobrecargas de entrega.`,
  },
  {
    id: "mod-labs",
    slug: "module-labs",
    title: "Labs: Incubadora de Ideias & Experimentos",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "🧪",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Espaço de experimentação rápida e validação de hipóteses antes da criação de workspaces oficiais.",
    sourceFilePath: "docs/modules/labs.md",
    tags: ["labs", "experimentos", "hipoteses", "musa"],
    content: `Incubadora de projetos embrionários sugerida pela Musa para testar tração antes de formalizar compromissos.`,
  },
  {
    id: "mod-trash",
    slug: "module-trash",
    title: "Lixeira: Retenção de 10 Dias com Desfazer",
    category: "modules",
    categoryLabel: "Módulos Especializados",
    icon: "🗑️",
    status: "IMPLEMENTED",
    lastVerified: "2026-08-29",
    summary: "Ambiente de quarentena segura com restauração em 1 clique e purga automática programada.",
    sourceFilePath: "docs/varynth/trash.md",
    tags: ["lixeira", "trash", "undo", "quarentena"],
    relatedADRs: ["ADR-002"],
    content: `Garantia de que nenhum recurso é excluído permanentemente no ato, permitindo restauração completa em 10 dias.`,
  },
];

