import assert from "node:assert/strict";
import { DEFAULT_DOMAIN_DEFINITIONS, DomainRegistry, mergeDomainDefinitions } from "./domain-registry";

const registry = new DomainRegistry();
registry.register({ id: "music", label: "Music", specialists: [], capabilities: [], relatedDomains: [], enabled: true });
registry.register({ id: "music.game-audio", label: "Game Audio", parentId: "music", specialists: [], capabilities: [], relatedDomains: [], enabled: true });
registry.registerOwner("music", "euterpe");
registry.registerCoOwner("music", "music-coordinator");
registry.transferOwnership("music", "future-euterpe");
registry.registerSpecialist("music.game-audio", "game-agent");
registry.registerCapability("music", "music.explainTheory");
assert.equal(registry.resolveOwner("music.game-audio"), "future-euterpe");
assert.equal(registry.getDomain("music")?.ownershipHistory?.[0]?.agentId, "euterpe");
assert.deepEqual(registry.resolveCoOwners("music"), ["music-coordinator"]);
assert.deepEqual(registry.resolveSpecialists("music"), ["future-euterpe", "music-coordinator"]);
const exposedDomain = registry.getDomain("music")!;
exposedDomain.specialists.push("unauthorized-agent");
assert.deepEqual(registry.resolveSpecialists("music"), ["future-euterpe", "music-coordinator"]);
assert.deepEqual(registry.resolveKnowledgePolicy("music")?.allowedVisibility, ["DOMAIN", "CROSS_DOMAIN", "PUBLIC_TO_AGENTS"]);
assert.equal(registry.getAwarenessIndex().contentLoaded, false);
assert.deepEqual(registry.resolveSpecialists("music.game-audio"), ["game-agent", "future-euterpe", "music-coordinator"]);
assert.ok(registry.getAwarenessIndex().domains.find((domain) => domain.id === "music")?.coOwners.includes("music-coordinator"));
assert.ok(registry.resolveRelatedDomains("music").includes("music.game-audio"));
assert.equal(registry.listHierarchy("music").length, 2);
assert.throws(() => registry.register({ id: "music", label: "Cycle", parentId: "music.game-audio", specialists: [], capabilities: [], relatedDomains: [], enabled: true }), /DOMAIN_HIERARCHY_CYCLE/);
assert.throws(() => registry.register({ id: "music.game-audio", label: "Cycle", parentId: "music.game-audio", specialists: [], capabilities: [], relatedDomains: [], enabled: true }), /DOMAIN_HIERARCHY_CYCLE/);
const restored = new DomainRegistry(false);
restored.replaceDomains(registry.listAllDomains());
assert.deepEqual(restored.listAllDomains(), registry.listAllDomains());
restored.removeCoOwner("music", "music-coordinator");
assert.equal(restored.resolveCoOwners("music").includes("music-coordinator"), false);
assert.equal(restored.resolveSpecialists("music.game-audio").includes("music-coordinator"), false);
assert.throws(() => restored.registerCoOwner("music", "future-euterpe"), /DOMAIN_CO_OWNER_IS_PRIMARY/);
assert.throws(() => restored.removeCoOwner("music", "missing-agent"), /DOMAIN_CO_OWNER_NOT_FOUND/);
restored.registerSpecialist("music", "dual-role-agent");
restored.registerCoOwner("music", "dual-role-agent");
restored.removeCoOwner("music", "dual-role-agent");
assert.ok(restored.resolveSpecialists("music").includes("dual-role-agent"), "removing co-ownership must retain an independently registered specialist role");
const merged = new DomainRegistry(false);
merged.replaceDomains(mergeDomainDefinitions(DEFAULT_DOMAIN_DEFINITIONS, [{ id: "music", label: "Custom Music", primaryOwner: "custom-owner", specialists: ["custom-owner"], capabilities: [], relatedDomains: [], enabled: true }]));
assert.equal(merged.getDomain("music.theory.harmony")?.parentId, "music.theory");
assert.equal(merged.resolveOwner("music.theory.harmony"), "custom-owner");
assert.ok(merged.listHierarchy("legal").some((domain) => domain.id === "legal.intellectual-property"));
assert.ok(merged.resolveCapabilities("music.theory.harmony").includes("music.explainTheory"));
assert.equal(merged.isWithinDomain("legal.intellectual-property", "legal"), true);
assert.equal(merged.isWithinDomain("legal", "legal.intellectual-property"), false);
assert.equal(merged.isWithinDomain("music.theory.harmony", "legal"), false);
assert.ok(merged.resolvePublicCapabilities("music").some((capability) => capability.id === "music.explainHarmony"));
assert.ok(!merged.resolvePublicCapabilities("system.orchestration").length);
const migrated = new DomainRegistry(false);
migrated.replaceDomains(mergeDomainDefinitions(DEFAULT_DOMAIN_DEFINITIONS, [{ id: "music", label: "Music (stored)", primaryOwner: "euterpe", specialists: ["euterpe"], capabilities: ["music.inspectMetadata"], relatedDomains: [], enabled: true }]));
assert.ok(migrated.resolvePublicCapabilities("music").some((capability) => capability.id === "music.inspectMetadata"));
const revoked = new DomainRegistry(false);
revoked.replaceDomains(mergeDomainDefinitions(DEFAULT_DOMAIN_DEFINITIONS, [{ id: "music", label: "Music", primaryOwner: "euterpe", specialists: ["euterpe"], capabilities: ["music.inspectMetadata"], publicCapabilities: [], relatedDomains: [], enabled: true }]));
assert.equal(revoked.resolvePublicCapabilities("music").some((capability) => capability.domain === "music"), false);
assert.throws(() => merged.register({ id: "unsafe", label: "Unsafe", primaryOwner: "agent", specialists: [], capabilities: ["unsafe.execute"], publicCapabilities: [{ id: "unsafe.execute", description: "", input: ["query"], output: ["result"], allowedConsumers: ["*"] }], relatedDomains: [], enabled: true }), /DOMAIN_PUBLIC_CAPABILITY_INVALID/);
const defaultsWithCoOwner = [{ id: "shared", label: "Shared", coOwners: ["baseline-co-owner"], specialists: [], capabilities: [], relatedDomains: [], enabled: true }];
assert.deepEqual(mergeDomainDefinitions(defaultsWithCoOwner, [{ id: "shared", label: "Persisted", specialists: [], capabilities: [], relatedDomains: [], enabled: true }])[0].coOwners, ["baseline-co-owner"]);
assert.deepEqual(mergeDomainDefinitions(defaultsWithCoOwner, [{ id: "shared", label: "Persisted", coOwners: [], specialists: [], capabilities: [], relatedDomains: [], enabled: true }])[0].coOwners, [], "explicit empty co-owner list must revoke inherited defaults");
const defaultsWithRouting = [{ id: "routed", label: "Routed", routingTerms: ["baseline phrase"], routingPriority: 12, specialists: [], capabilities: [], relatedDomains: [], enabled: true }];
assert.deepEqual(mergeDomainDefinitions(defaultsWithRouting, [{ id: "routed", label: "Persisted", specialists: [], capabilities: [], relatedDomains: [], enabled: true }])[0].routingTerms, ["baseline phrase"]);
assert.deepEqual(mergeDomainDefinitions(defaultsWithRouting, [{ id: "routed", label: "Persisted", routingTerms: [], routingPriority: 0, specialists: [], capabilities: [], relatedDomains: [], enabled: true }])[0].routingTerms, [], "explicit empty routing terms must disable inherited routes");
const routingRegistry = new DomainRegistry(false);
routingRegistry.register({ id: "routing-test", label: "Routing Test", specialists: [], capabilities: [], relatedDomains: [], enabled: true });
routingRegistry.setRouting("routing-test", ["first term", "first term"], 4);
assert.deepEqual(routingRegistry.getDomain("routing-test")?.routingTerms, ["first term"]);
assert.throws(() => routingRegistry.setRouting("routing-test", [""], 4), /DOMAIN_ROUTING_TERMS_INVALID/);
assert.throws(() => routingRegistry.setRouting("routing-test", ["valid"], 1001), /DOMAIN_ROUTING_PRIORITY_INVALID/);
const bridgeRegistry = new DomainRegistry(false);
bridgeRegistry.register({ id: "law", label: "Law", primaryOwner: "law-agent", specialists: [], capabilities: [], relatedDomains: [], enabled: true });
bridgeRegistry.register({ id: "music", label: "Music", primaryOwner: "music-agent", specialists: [], capabilities: [], relatedDomains: [], enabled: true });
bridgeRegistry.registerDomainBridge("law", { id: "law-music", domains: ["law", "music"], concepts: ["licensing", "chain of title"], description: "Rights meet provenance.", enabled: true });
assert.deepEqual(bridgeRegistry.resolveDomainBridges("music")[0]?.concepts, ["licensing", "chain of title"]);
assert.ok(bridgeRegistry.resolveRelatedDomains("music").includes("law"), "bridges resolve symmetrically");
const bridgeCopy = bridgeRegistry.getDomain("law")!;
bridgeCopy.bridges![0].concepts.push("mutated");
assert.deepEqual(bridgeRegistry.resolveDomainBridges("law")[0]?.concepts, ["licensing", "chain of title"], "bridge results are deeply cloned");
assert.throws(() => bridgeRegistry.registerDomainBridge("law", { id: "law-music-2", domains: ["law", "missing"], concepts: ["x"], description: "bad", enabled: true }), /DOMAIN_BRIDGE_DOMAIN_NOT_FOUND/);
const bridgeSnapshot = new DomainRegistry(false);
bridgeSnapshot.replaceDomains(bridgeRegistry.listAllDomains());
assert.deepEqual(bridgeSnapshot.listDomainBridges(), bridgeRegistry.listDomainBridges(), "bridges persist through registry snapshots");
bridgeSnapshot.removeDomainBridge("law", "law-music");
assert.equal(bridgeSnapshot.resolveDomainBridges("music").length, 0);
const explicitBridgeRevocation = mergeDomainDefinitions([{ id: "r", label: "R", bridges: [{ id: "r-s", domains: ["r", "s"], concepts: ["term"], description: "desc", enabled: true }], specialists: [], capabilities: [], relatedDomains: [], enabled: true }], [{ id: "r", label: "R", bridges: [], specialists: [], capabilities: [], relatedDomains: [], enabled: true }]);
assert.deepEqual(explicitBridgeRevocation[0].bridges, [], "explicit empty bridge list revokes baseline bridges");
console.log("Domain registry tests passed");
