import assert from "node:assert/strict";
import { routeKnowledgeIntent } from "./router";

const route = routeKnowledgeIntent({ task: "verifique o copyright da trilha do jogo" });
assert.equal(route.primaryDomain, "legal.intellectual-property");
assert.deepEqual(route.relatedDomains, ["music.asset-provenance"]);
assert.equal(route.owner, "justitia");
assert.equal(route.recommendedDelegation, true);
assert.equal(routeKnowledgeIntent({ task: "algo sem domínio conhecido" }).recommendedDelegation, false);
const harmony = routeKnowledgeIntent({ task: "Explique a harmonia e os acordes" });
assert.equal(harmony.primaryDomain, "music.theory.harmony");
assert.equal(harmony.owner, "euterpe");
const gameAudio = routeKnowledgeIntent({ task: "Crie adaptive music e game audio para meu jogo" });
assert.equal(gameAudio.primaryDomain, "music.game-audio");
assert.equal(gameAudio.owner, "euterpe");
const licensing = routeKnowledgeIntent({ task: "Verifique a licença e copyright da música desta trilha" });
assert.equal(licensing.primaryDomain, "legal.intellectual-property");
assert.equal(licensing.owner, "justitia");
assert.ok(licensing.relatedDomains.includes("music.asset-provenance"));
const genericLegal = routeKnowledgeIntent({ task: "Quais são os limites de propriedade intelectual de uma patente?" });
assert.equal(genericLegal.primaryDomain, "legal.intellectual-property");
assert.deepEqual(genericLegal.relatedDomains, []);
console.log("Knowledge router tests passed");
