import assert from "node:assert/strict";
import { DomainRegistry } from "./domain-registry";
import { routeKnowledgeIntent } from "./router";

const route = routeKnowledgeIntent({ task: "verifique o copyright da trilha do jogo" });
assert.equal(route.primaryDomain, "legal.intellectual-property");
assert.ok(route.relatedDomains.includes("music.asset-provenance"));
assert.ok(route.relatedDomains.includes("music.game-audio"));
assert.ok(route.relatedDomains.includes("game-development"));
assert.equal(route.owner, "justitia");
assert.equal(route.recommendedDelegation, true);
assert.ok(route.matchedDomains[0].matchedTerms.length > 0, "the route should expose the registered evidence that selected it");
assert.equal(routeKnowledgeIntent({ task: "algo sem domínio conhecido" }).recommendedDelegation, false);
const harmony = routeKnowledgeIntent({ task: "Explique a harmonia e os acordes" });
assert.equal(harmony.primaryDomain, "music.theory.harmony");
assert.equal(harmony.owner, "euterpe");
const gameAudio = routeKnowledgeIntent({ task: "Crie adaptive music e game audio para meu jogo" });
assert.equal(gameAudio.primaryDomain, "music.game-audio");
assert.equal(gameAudio.owner, "euterpe");
const licensing = routeKnowledgeIntent({ task: "Verifique a licença e copyright da música desta trilha" });
assert.equal(licensing.primaryDomain, "legal.intellectual-property");
assert.equal(licensing.owner, "justitia");
assert.ok(licensing.relatedDomains.includes("music.asset-provenance"));
const genericLegal = routeKnowledgeIntent({ task: "Quais são os limites de propriedade intelectual de uma patente?" });
assert.equal(genericLegal.primaryDomain, "legal.intellectual-property");
assert.ok(genericLegal.relatedDomains.includes("music.asset-provenance"), "domain registry relationships remain discoverable for a legal domain");
const interdisciplinary = routeKnowledgeIntent({ task: "Prepare a trilha sonora adaptativa do jogo e verifique a licença comercial" });
assert.equal(interdisciplinary.primaryDomain, "legal.intellectual-property");
assert.ok(interdisciplinary.relatedDomains.includes("music.game-audio"));
assert.ok(interdisciplinary.relatedDomains.includes("game-development"));
assert.ok(interdisciplinary.specialists.includes("justitia"));
assert.ok(interdisciplinary.specialists.includes("euterpe"), "multi-domain routing should expose specialists for every matched domain");

const extensibleRegistry = new DomainRegistry(false);
extensibleRegistry.register({ id: "climate-resilience", label: "Climate Resilience", primaryOwner: "climate-agent", specialists: [], capabilities: ["climate.assessRisk"], routingTerms: ["mudança climática", "climate resilience"], routingPriority: 120, relatedDomains: [], enabled: true });
const dynamic = routeKnowledgeIntent({ task: "Planeje adaptação à MUDANÇA CLIMATICA", registry: extensibleRegistry });
assert.equal(dynamic.primaryDomain, "climate-resilience", "new registered domains should route without editing router code");
assert.equal(dynamic.owner, "climate-agent");
assert.deepEqual(dynamic.matchedDomains[0].matchedTerms, ["mudança climática"]);
extensibleRegistry.setRouting("climate-resilience", ["resiliência territorial"], 130);
assert.equal(routeKnowledgeIntent({ task: "resiliência territorial", registry: extensibleRegistry }).primaryDomain, "climate-resilience");
assert.equal(routeKnowledgeIntent({ task: "mudança climática", registry: extensibleRegistry }).primaryDomain, undefined, "replacing registry routing terms must remove stale matches");
const bridgeRegistry = new DomainRegistry(false);
bridgeRegistry.register({ id: "interactive-design", label: "Interactive Design", primaryOwner: "designer", specialists: [], capabilities: [], routingTerms: ["gameplay"], routingPriority: 20, relatedDomains: [], enabled: true });
bridgeRegistry.register({ id: "audio-engineering", label: "Audio Engineering", primaryOwner: "composer", specialists: [], capabilities: ["audio.adaptive"], routingTerms: [], routingPriority: 10, relatedDomains: [], enabled: true });
bridgeRegistry.registerDomainBridge("interactive-design", { id: "interactive-audio", domains: ["interactive-design", "audio-engineering"], concepts: ["adaptive soundscape"], description: "Bridges player interaction and responsive sound.", enabled: true });
const bridgeRoute = routeKnowledgeIntent({ task: "Build an adaptive soundscape", registry: bridgeRegistry });
assert.equal(bridgeRoute.primaryDomain, "interactive-design");
assert.ok(bridgeRoute.relatedDomains.includes("audio-engineering"));
assert.ok(bridgeRoute.specialists.includes("composer"));
assert.ok(bridgeRoute.reason.includes("DomainBridge"));
console.log("Knowledge router tests passed");
