import { VideoTrack, VideoScene, VideoTimeline } from "./types";
import { FPS_30, FPS_24, FPS_29_97 } from "../temporal/temporal-core";

export interface VideoTemplate {
  id: string;
  name: string;
  description: string;
  timeline: Omit<VideoTimeline, "zoom" | "snapToGrid" | "timeUnit">;
  initialScenes: VideoScene[];
  initialTracks: VideoTrack[];
}

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  {
    id: "blank",
    name: "Vídeo em Branco (16:9)",
    description: "Linha do tempo limpa em Full HD (1920×1080 @ 30fps) com 30 segundos de duração.",
    timeline: {
      durationMs: 30000,
      width: 1920,
      height: 1080,
      frameRate: FPS_30,
      markers: [],
    },
    initialScenes: [
      {
        id: "scene-1",
        name: "Cena Principal",
        startMs: 0,
        endMs: 30000,
        description: "Cena única inicial",
        relatedClipIds: [],
      },
    ],
    initialTracks: [
      {
        id: "track-video-main",
        name: "Vídeo Principal",
        type: "VIDEO",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-audio-voice",
        name: "Voz / Narração",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 2,
        volume: 1.0,
        pan: 0.0,
        muted: false,
        solo: false,
        clips: [],
        color: "#10b981",
      },
      {
        id: "track-audio-music",
        name: "Trilha Sonora",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 3,
        volume: 0.5,
        pan: 0.0,
        muted: false,
        solo: false,
        clips: [],
        color: "#8b5cf6",
      },
    ],
  },
  {
    id: "landscape-16-9",
    name: "Produção Editorial (16:9 Full HD)",
    description: "Estrutura clássica de 3 cenas (Introdução, Desenvolvimento e Conclusão) com faixas de vídeo, texto e trilha.",
    timeline: {
      durationMs: 60000,
      width: 1920,
      height: 1080,
      frameRate: FPS_30,
      markers: [
        { id: "m-intro", timeMs: 0, label: "Introdução", color: "#3b82f6" },
        { id: "m-body", timeMs: 15000, label: "Desenvolvimento", color: "#10b981" },
        { id: "m-outro", timeMs: 45000, label: "Encerramento", color: "#ef4444" },
      ],
    },
    initialScenes: [
      {
        id: "scene-intro",
        name: "1. Introdução",
        startMs: 0,
        endMs: 15000,
        description: "Abertura com títulos e gancho narrativo",
        relatedClipIds: [],
      },
      {
        id: "scene-body",
        name: "2. Tópico Principal",
        startMs: 15000,
        endMs: 45000,
        description: "Explanação e demonstração visual",
        relatedClipIds: [],
      },
      {
        id: "scene-outro",
        name: "3. Conclusão",
        startMs: 45000,
        endMs: 60000,
        description: "Resumo executivo e créditos",
        relatedClipIds: [],
      },
    ],
    initialTracks: [
      {
        id: "track-text-overlay",
        name: "Títulos & Overlays",
        type: "TEXT",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        color: "#f59e0b",
      },
      {
        id: "track-video-b-roll",
        name: "B-Roll / Imagens",
        type: "IMAGE",
        visible: true,
        locked: false,
        order: 2,
        clips: [],
        color: "#06b6d4",
      },
      {
        id: "track-video-a-roll",
        name: "Vídeo Principal",
        type: "VIDEO",
        visible: true,
        locked: false,
        order: 3,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-voice",
        name: "Voz",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 4,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        color: "#10b981",
      },
      {
        id: "track-music",
        name: "Música de Fundo",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 5,
        volume: 0.45,
        pan: 0.0,
        clips: [],
        color: "#8b5cf6",
      },
    ],
  },
  {
    id: "vertical-9-16",
    name: "Vídeo Vertical (9:16 Shorts / Reels)",
    description: "Formato vertical 1080×1920 otimizado para vídeos curtos com faixa dedicada de legendas e títulos dinâmicos.",
    timeline: {
      durationMs: 30000,
      width: 1080,
      height: 1920,
      frameRate: FPS_30,
      markers: [],
    },
    initialScenes: [
      {
        id: "scene-reel",
        name: "Reel Completo",
        startMs: 0,
        endMs: 30000,
        relatedClipIds: [],
      },
    ],
    initialTracks: [
      {
        id: "track-subtitles",
        name: "Legendas Automáticas",
        type: "SUBTITLE",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        subtitles: [],
        color: "#eab308",
      },
      {
        id: "track-stickers",
        name: "Textos & Destaques",
        type: "TEXT",
        visible: true,
        locked: false,
        order: 2,
        clips: [],
        color: "#ec4899",
      },
      {
        id: "track-main-video",
        name: "Vídeo Vertical",
        type: "VIDEO",
        visible: true,
        locked: false,
        order: 3,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-voice",
        name: "Locução",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 4,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        color: "#10b981",
      },
    ],
  },
  {
    id: "square-1-1",
    name: "Vídeo Quadrado (1:1 Social Post)",
    description: "Composição quadrada 1080×1080 para feed de notícias e resumos visuais.",
    timeline: {
      durationMs: 30000,
      width: 1080,
      height: 1080,
      frameRate: FPS_30,
      markers: [],
    },
    initialScenes: [
      { id: "scene-1", name: "Cena 1", startMs: 0, endMs: 30000, relatedClipIds: [] },
    ],
    initialTracks: [
      {
        id: "track-title",
        name: "Lower Thirds",
        type: "TEXT",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        color: "#f59e0b",
      },
      {
        id: "track-video",
        name: "Vídeo",
        type: "VIDEO",
        visible: true,
        locked: false,
        order: 2,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-audio",
        name: "Áudio",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 3,
        clips: [],
        color: "#10b981",
      },
    ],
  },
  {
    id: "presentation-video",
    name: "Slideshow Narrado & Apresentação",
    description: "Apresentação com troca de slides visuais, apresentador em picture-in-picture e narração contínua.",
    timeline: {
      durationMs: 90000,
      width: 1920,
      height: 1080,
      frameRate: FPS_30,
      markers: [
        { id: "m-slide1", timeMs: 0, label: "Slide 1", color: "#3b82f6" },
        { id: "m-slide2", timeMs: 30000, label: "Slide 2", color: "#06b6d4" },
        { id: "m-slide3", timeMs: 60000, label: "Slide 3", color: "#10b981" },
      ],
    },
    initialScenes: [
      { id: "scene-s1", name: "Slide 1: Problema", startMs: 0, endMs: 30000, relatedClipIds: [] },
      { id: "scene-s2", name: "Slide 2: Solução", startMs: 30000, endMs: 60000, relatedClipIds: [] },
      { id: "scene-s3", name: "Slide 3: Conclusão", startMs: 60000, endMs: 90000, relatedClipIds: [] },
    ],
    initialTracks: [
      {
        id: "track-slides",
        name: "Slides (Imagens)",
        type: "IMAGE",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        color: "#06b6d4",
      },
      {
        id: "track-presenter",
        name: "Apresentador (Vídeo)",
        type: "VIDEO",
        visible: true,
        locked: false,
        order: 2,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-voice",
        name: "Narração",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 3,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        color: "#10b981",
      },
    ],
  },
  {
    id: "narrated-slideshow",
    name: "História Visual / Slideshow Cinematográfico",
    description: "4 cenas cinematográficas com proporção 16:9 a 24fps com transições suaves e ambiência acústica.",
    timeline: {
      durationMs: 45000,
      width: 1920,
      height: 1080,
      frameRate: FPS_24,
      markers: [],
    },
    initialScenes: [
      { id: "sc-1", name: "Ato 1: O Início", startMs: 0, endMs: 12000, relatedClipIds: [] },
      { id: "sc-2", name: "Ato 2: O Conflito", startMs: 12000, endMs: 25000, relatedClipIds: [] },
      { id: "sc-3", name: "Ato 3: A Virada", startMs: 25000, endMs: 35000, relatedClipIds: [] },
      { id: "sc-4", name: "Ato 4: O Epílogo", startMs: 35000, endMs: 45000, relatedClipIds: [] },
    ],
    initialTracks: [
      {
        id: "track-visuals",
        name: "Artes & Fotografias",
        type: "IMAGE",
        visible: true,
        locked: false,
        order: 1,
        clips: [],
        color: "#8b5cf6",
      },
      {
        id: "track-voice",
        name: "Narração",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 2,
        volume: 1.0,
        pan: 0.0,
        clips: [],
        color: "#3b82f6",
      },
      {
        id: "track-ambience",
        name: "Ambiência Sonora",
        type: "AUDIO",
        visible: true,
        locked: false,
        order: 3,
        volume: 0.4,
        pan: 0.0,
        clips: [],
        color: "#64748b",
      },
    ],
  },
];

