import { GameDocumentState, GameType } from "./types";

export interface GameTemplate {
  id: string;
  name: string;
  description: string;
  gameType: GameType;
  iconName: string;
  createDocumentState: (artifactId: string) => GameDocumentState;
}

export const GAME_TEMPLATES: GameTemplate[] = [
  {
    id: "blank-2d",
    name: "Projeto 2D em Branco",
    description: "Template mínimo com cena inicial, câmera 2D e entidade de jogador básica.",
    gameType: "2D",
    iconName: "Square",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-main",
      scenes: [
        {
          id: "scene-main",
          name: "Cena Principal",
          description: "Cena base do projeto 2D",
          backgroundColor: "#0d0f18",
          entityIds: ["entity-player"],
          ruleIds: ["rule-start"],
        },
      ],
      entities: [
        {
          id: "entity-player",
          sceneId: "scene-main",
          name: "Player",
          active: true,
          tags: ["player"],
          components: [
            { type: "TRANSFORM", x: 400, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "default-player-sprite", width: 64, height: 64 },
            { type: "COLLIDER", shape: "RECTANGLE", width: 64, height: 64 },
            { type: "INPUT", actions: { MOVE_LEFT: ["ArrowLeft", "KeyA"], MOVE_RIGHT: ["ArrowRight", "KeyD"], MOVE_UP: ["ArrowUp", "KeyW"], MOVE_DOWN: ["ArrowDown", "KeyS"] } },
          ],
        },
      ],
      variables: [
        { id: "var-score", name: "score", type: "NUMBER", initialValue: 0 },
        { id: "var-health", name: "health", type: "NUMBER", initialValue: 100 },
      ],
      rules: [
        {
          id: "rule-start",
          name: "Iniciar Jogo",
          enabled: true,
          trigger: { type: "ON_START" },
          conditions: [],
          actions: [{ type: "SHOW_TEXT", text: "Bem-vindo ao VARYNTH Game Studio!" }],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "MOVE_LEFT", keys: ["ArrowLeft", "KeyA"], description: "Mover para a esquerda" },
        { action: "MOVE_RIGHT", keys: ["ArrowRight", "KeyD"], description: "Mover para a direita" },
        { action: "INTERACT", keys: ["KeyE", "Space"], description: "Interagir" },
      ],
      selectedSceneId: "scene-main",
      selectedEntityIds: ["entity-player"],
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: "quiz",
    name: "Quiz Interativo / Perguntas",
    description: "Template estruturado para perguntas e respostas com controle de pontuação e transição de telas.",
    gameType: "QUIZ",
    iconName: "HelpCircle",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-q1",
      scenes: [
        {
          id: "scene-q1",
          name: "Questão 1: Princípio da Legalidade",
          description: "Primeira pergunta do quiz",
          backgroundColor: "#101222",
          nextSceneIds: ["scene-q2"],
          entityIds: ["entity-q1-title", "entity-opt-a", "entity-opt-b"],
          ruleIds: ["rule-correct-q1", "rule-wrong-q1"],
        },
        {
          id: "scene-q2",
          name: "Questão 2: Culpabilidade",
          description: "Segunda pergunta do quiz",
          backgroundColor: "#101222",
          nextSceneIds: ["scene-victory"],
          entityIds: ["entity-q2-title"],
          ruleIds: [],
        },
        {
          id: "scene-victory",
          name: "Tela de Resultado",
          description: "Apresenta a pontuação final",
          backgroundColor: "#0a1912",
          entityIds: ["entity-result-text"],
          ruleIds: [],
        },
      ],
      entities: [
        {
          id: "entity-q1-title",
          sceneId: "scene-q1",
          name: "Texto da Pergunta 1",
          active: true,
          tags: ["ui", "text"],
          components: [
            { type: "TRANSFORM", x: 400, y: 150, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "Não há crime sem lei anterior que o defina. Qual é este princípio?", fontSize: 20, color: "#ffffff", alignment: "center" },
          ],
        },
        {
          id: "entity-opt-a",
          sceneId: "scene-q1",
          name: "Opção A: Legalidade (Correta)",
          active: true,
          tags: ["ui", "button"],
          components: [
            { type: "TRANSFORM", x: 400, y: 280, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "A) Princípio da Legalidade" },
            { type: "COLLIDER", shape: "RECTANGLE", width: 350, height: 50 },
          ],
        },
        {
          id: "entity-opt-b",
          sceneId: "scene-q1",
          name: "Opção B: Insignificância",
          active: true,
          tags: ["ui", "button"],
          components: [
            { type: "TRANSFORM", x: 400, y: 350, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "B) Princípio da Insignificância" },
            { type: "COLLIDER", shape: "RECTANGLE", width: 350, height: 50 },
          ],
        },
        {
          id: "entity-q2-title",
          sceneId: "scene-q2",
          name: "Texto da Pergunta 2",
          active: true,
          tags: ["ui", "text"],
          components: [
            { type: "TRANSFORM", x: 400, y: 150, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "A culpabilidade é pressuposto da aplicação da pena?", fontSize: 20, color: "#ffffff", alignment: "center" },
          ],
        },
        {
          id: "entity-result-text",
          sceneId: "scene-victory",
          name: "Texto de Conclusão",
          active: true,
          tags: ["ui", "text"],
          components: [
            { type: "TRANSFORM", x: 400, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "Parabéns! Você concluiu o Quiz com sucesso.", fontSize: 24, color: "#22c55e", alignment: "center" },
          ],
        },
      ],
      variables: [
        { id: "var-score", name: "score", type: "NUMBER", initialValue: 0 },
        { id: "var-currentQuestion", name: "currentQuestion", type: "NUMBER", initialValue: 1 },
      ],
      rules: [
        {
          id: "rule-correct-q1",
          name: "Acertou Questão 1",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-opt-a" },
          conditions: [],
          actions: [
            { type: "ADD_VARIABLE", variableId: "var-score", value: 10 },
            { type: "SHOW_TEXT", text: "Resposta correta! +10 pontos." },
            { type: "CHANGE_SCENE", targetSceneId: "scene-q2" },
          ],
        },
        {
          id: "rule-wrong-q1",
          name: "Errou Questão 1",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-opt-b" },
          conditions: [],
          actions: [
            { type: "SHOW_TEXT", text: "Incorreto! Tente novamente." },
          ],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "SELECT_OPTION_A", keys: ["Digit1", "KeyA"], description: "Selecionar Opção A" },
        { action: "SELECT_OPTION_B", keys: ["Digit2", "KeyB"], description: "Selecionar Opção B" },
        { action: "NEXT_QUESTION", keys: ["Space", "Enter"], description: "Próxima Pergunta" },
      ],
      selectedSceneId: "scene-q1",
      selectedEntityIds: ["entity-q1-title"],
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: "interactive-story",
    name: "História Interativa / Narrativa Ramificada",
    description: "Narrativa com diálogos, nós de escolhas, variáveis de relacionamento e múltiplos finais.",
    gameType: "INTERACTIVE_STORY",
    iconName: "BookOpen",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-intro",
      scenes: [
        {
          id: "scene-intro",
          name: "A Chegada ao Escritório",
          description: "Primeira cena da narrativa",
          backgroundColor: "#13141f",
          nextSceneIds: ["scene-investigate", "scene-interrogate"],
          entityIds: ["entity-dialogue-box", "entity-choice-1", "entity-choice-2"],
          ruleIds: ["rule-choose-investigate", "rule-choose-interrogate"],
        },
        {
          id: "scene-investigate",
          name: "Investigação dos Arquivos",
          description: "Análise de documentos",
          backgroundColor: "#0d131f",
          entityIds: ["entity-clue-doc"],
          ruleIds: [],
        },
        {
          id: "scene-interrogate",
          name: "Interrogatório do Suspeito",
          description: "Conversa com a testemunha",
          backgroundColor: "#1f1012",
          entityIds: ["entity-suspect-npc"],
          ruleIds: [],
        },
      ],
      entities: [
        {
          id: "entity-dialogue-box",
          sceneId: "scene-intro",
          name: "Caixa de Diálogo",
          active: true,
          tags: ["dialogue", "ui"],
          components: [
            { type: "TRANSFORM", x: 400, y: 200, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "Um documento confidencial desapareceu da sala 304. Por onde você quer começar?", fontSize: 18, color: "#e2e8f0", alignment: "center" },
          ],
        },
        {
          id: "entity-choice-1",
          sceneId: "scene-intro",
          name: "Escolha 1: Examinar a sala",
          active: true,
          tags: ["button"],
          components: [
            { type: "TRANSFORM", x: 400, y: 320, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "1. Examinar a mesa e arquivos da sala" },
          ],
        },
        {
          id: "entity-choice-2",
          sceneId: "scene-intro",
          name: "Escolha 2: Interrogar o segurança",
          active: true,
          tags: ["button"],
          components: [
            { type: "TRANSFORM", x: 400, y: 390, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "2. Falar imediatamente com o segurança" },
          ],
        },
        {
          id: "entity-clue-doc",
          sceneId: "scene-investigate",
          name: "Documento com Impressões Digitais",
          active: true,
          tags: ["evidence"],
          components: [
            { type: "TRANSFORM", x: 400, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "Você encontrou uma cópia rasgada do contrato!", fontSize: 18, color: "#38bdf8", alignment: "center" },
          ],
        },
        {
          id: "entity-suspect-npc",
          sceneId: "scene-interrogate",
          name: "Segurança Marcos",
          active: true,
          tags: ["npc"],
          components: [
            { type: "TRANSFORM", x: 400, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "TEXT", text: "Marcos: 'Eu não vi ninguém entrar depois das 22h...'", fontSize: 18, color: "#f87171", alignment: "center" },
          ],
        },
      ],
      variables: [
        { id: "var-clueFound", name: "clueFound", type: "BOOLEAN", initialValue: false },
        { id: "var-suspectTrust", name: "suspectTrust", type: "NUMBER", initialValue: 50 },
      ],
      rules: [
        {
          id: "rule-choose-investigate",
          name: "Ir para Investigação",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-choice-1" },
          conditions: [],
          actions: [
            { type: "SET_VARIABLE", variableId: "var-clueFound", value: true },
            { type: "CHANGE_SCENE", targetSceneId: "scene-investigate" },
          ],
        },
        {
          id: "rule-choose-interrogate",
          name: "Ir para Interrogatório",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-choice-2" },
          conditions: [],
          actions: [
            { type: "CHANGE_SCENE", targetSceneId: "scene-interrogate" },
          ],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "CHOOSE_1", keys: ["Digit1", "KeyA"], description: "Escolher Primeira Opção" },
        { action: "CHOOSE_2", keys: ["Digit2", "KeyB"], description: "Escolher Segunda Opção" },
        { action: "ADVANCE_DIALOGUE", keys: ["Space", "Enter"], description: "Avançar Diálogo" },
      ],
      selectedSceneId: "scene-intro",
      selectedEntityIds: ["entity-dialogue-box"],
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: "top-down-prototype",
    name: "Protótipo Top-Down 2D",
    description: "Navegação em sala 2D, coleta de chave, porta trancada e colisão.",
    gameType: "WEB_2D",
    iconName: "Compass",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-dungeon",
      scenes: [
        {
          id: "scene-dungeon",
          name: "Masmorra / Sala 1",
          description: "Encontre a chave para abrir o portão",
          backgroundColor: "#0f172a",
          entityIds: ["entity-player", "entity-key", "entity-door"],
          ruleIds: ["rule-collect-key", "rule-open-door"],
        },
      ],
      entities: [
        {
          id: "entity-player",
          sceneId: "scene-dungeon",
          name: "Herói",
          active: true,
          tags: ["player"],
          components: [
            { type: "TRANSFORM", x: 150, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 2 },
            { type: "SPRITE", assetId: "hero-sprite", width: 48, height: 48 },
            { type: "COLLIDER", shape: "RECTANGLE", width: 48, height: 48 },
            { type: "INPUT", actions: { MOVE_LEFT: ["ArrowLeft"], MOVE_RIGHT: ["ArrowRight"], MOVE_UP: ["ArrowUp"], MOVE_DOWN: ["ArrowDown"] } },
          ],
        },
        {
          id: "entity-key",
          sceneId: "scene-dungeon",
          name: "Chave Dourada",
          active: true,
          tags: ["item", "key"],
          components: [
            { type: "TRANSFORM", x: 400, y: 150, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "key-sprite", width: 32, height: 32 },
            { type: "COLLIDER", shape: "CIRCLE", width: 32, height: 32, isTrigger: true },
          ],
        },
        {
          id: "entity-door",
          sceneId: "scene-dungeon",
          name: "Porta de Ferro",
          active: true,
          tags: ["door", "solid"],
          components: [
            { type: "TRANSFORM", x: 650, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "door-sprite", width: 48, height: 80 },
            { type: "COLLIDER", shape: "RECTANGLE", width: 48, height: 80 },
          ],
        },
      ],
      variables: [
        { id: "var-hasKey", name: "hasKey", type: "BOOLEAN", initialValue: false },
        { id: "var-doorUnlocked", name: "doorUnlocked", type: "BOOLEAN", initialValue: false },
      ],
      rules: [
        {
          id: "rule-collect-key",
          name: "Pegar Chave",
          enabled: true,
          trigger: { type: "ON_COLLISION", entityId: "entity-player", targetEntityId: "entity-key" },
          conditions: [{ variableId: "var-hasKey", operator: "EQUALS", value: false }],
          actions: [
            { type: "SET_VARIABLE", variableId: "var-hasKey", value: true },
            { type: "HIDE_ENTITY", entityId: "entity-key" },
            { type: "SHOW_TEXT", text: "Você pegou a Chave Dourada!" },
          ],
        },
        {
          id: "rule-open-door",
          name: "Abrir Porta",
          enabled: true,
          trigger: { type: "ON_COLLISION", entityId: "entity-player", targetEntityId: "entity-door" },
          conditions: [{ variableId: "var-hasKey", operator: "EQUALS", value: true }],
          actions: [
            { type: "SET_VARIABLE", variableId: "var-doorUnlocked", value: true },
            { type: "HIDE_ENTITY", entityId: "entity-door" },
            { type: "SHOW_TEXT", text: "Porta destrancada! Vitória!" },
            { type: "END_GAME" },
          ],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "MOVE_LEFT", keys: ["ArrowLeft", "KeyA"] },
        { action: "MOVE_RIGHT", keys: ["ArrowRight", "KeyD"] },
        { action: "MOVE_UP", keys: ["ArrowUp", "KeyW"] },
        { action: "MOVE_DOWN", keys: ["ArrowDown", "KeyS"] },
      ],
      selectedSceneId: "scene-dungeon",
      selectedEntityIds: ["entity-player"],
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: "platformer-prototype",
    name: "Protótipo de Plataforma 2D",
    description: "Mecânica de pulo, moedas coletáveis e linha de chegada.",
    gameType: "WEB_2D",
    iconName: "Layers",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-level1",
      scenes: [
        {
          id: "scene-level1",
          name: "Nível 1 - Montanhas",
          description: "Salte sobre as plataformas e colete 3 moedas",
          backgroundColor: "#1e293b",
          entityIds: ["entity-runner", "entity-coin1", "entity-coin2", "entity-flag"],
          ruleIds: ["rule-coin-1"],
        },
      ],
      entities: [
        {
          id: "entity-runner",
          sceneId: "scene-level1",
          name: "Corredor",
          active: true,
          tags: ["player"],
          components: [
            { type: "TRANSFORM", x: 100, y: 400, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 2 },
            { type: "SPRITE", assetId: "runner-sprite", width: 48, height: 64 },
            { type: "COLLIDER", shape: "RECTANGLE", width: 48, height: 64 },
            { type: "INPUT", actions: { MOVE_RIGHT: ["ArrowRight", "KeyD"], JUMP: ["Space", "ArrowUp"] } },
          ],
        },
        {
          id: "entity-coin1",
          sceneId: "scene-level1",
          name: "Moeda de Ouro 1",
          active: true,
          tags: ["coin", "collectible"],
          components: [
            { type: "TRANSFORM", x: 300, y: 350, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "coin-sprite", width: 32, height: 32 },
            { type: "COLLIDER", shape: "CIRCLE", width: 32, height: 32, isTrigger: true },
          ],
        },
        {
          id: "entity-coin2",
          sceneId: "scene-level1",
          name: "Moeda de Ouro 2",
          active: true,
          tags: ["coin", "collectible"],
          components: [
            { type: "TRANSFORM", x: 500, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "coin-sprite", width: 32, height: 32 },
            { type: "COLLIDER", shape: "CIRCLE", width: 32, height: 32, isTrigger: true },
          ],
        },
        {
          id: "entity-flag",
          sceneId: "scene-level1",
          name: "Bandeira Final",
          active: true,
          tags: ["goal"],
          components: [
            { type: "TRANSFORM", x: 700, y: 380, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "SPRITE", assetId: "flag-sprite", width: 48, height: 80 },
            { type: "COLLIDER", shape: "RECTANGLE", width: 48, height: 80, isTrigger: true },
          ],
        },
      ],
      variables: [
        { id: "var-coins", name: "coins", type: "NUMBER", initialValue: 0 },
        { id: "var-levelComplete", name: "levelComplete", type: "BOOLEAN", initialValue: false },
      ],
      rules: [
        {
          id: "rule-coin-1",
          name: "Coletar Moeda 1",
          enabled: true,
          trigger: { type: "ON_COLLISION", entityId: "entity-runner", targetEntityId: "entity-coin1" },
          conditions: [],
          actions: [
            { type: "ADD_VARIABLE", variableId: "var-coins", value: 1 },
            { type: "HIDE_ENTITY", entityId: "entity-coin1" },
            { type: "SHOW_TEXT", text: "+1 Moeda Coletada!" },
          ],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "MOVE_RIGHT", keys: ["ArrowRight", "KeyD"] },
        { action: "JUMP", keys: ["Space", "ArrowUp"] },
      ],
      selectedSceneId: "scene-level1",
      selectedEntityIds: ["entity-runner"],
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: "investigation-game",
    name: "Jogo de Investigação Criminal",
    description: "Examine evidências, interrogue suspeitos e deduza a autoria do crime com veredicto final.",
    gameType: "INTERACTIVE_STORY",
    iconName: "Shield",
    createDocumentState: (artifactId: string): GameDocumentState => ({
      artifactId,
      entrySceneId: "scene-crime-room",
      scenes: [
        {
          id: "scene-crime-room",
          name: "Cena do Crime (Gabinete)",
          description: "Analise as 5 evidências presentes na sala",
          backgroundColor: "#181313",
          nextSceneIds: ["scene-verdict"],
          entityIds: ["entity-ev-fingerprint", "entity-ev-receipt", "entity-btn-verdict"],
          ruleIds: ["rule-inspect-fingerprint", "rule-inspect-receipt", "rule-go-verdict"],
        },
        {
          id: "scene-verdict",
          name: "Tribunal de Veredicto",
          description: "Aponte o suspeito culpado",
          backgroundColor: "#1c140e",
          entityIds: ["entity-suspect-1", "entity-suspect-2"],
          ruleIds: ["rule-accuse-culprit"],
        },
      ],
      entities: [
        {
          id: "entity-ev-fingerprint",
          sceneId: "scene-crime-room",
          name: "Evidência 1: Impressão no Copo",
          active: true,
          tags: ["evidence"],
          components: [
            { type: "TRANSFORM", x: 250, y: 250, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "🔍 Analisar Copo de Vidro" },
          ],
        },
        {
          id: "entity-ev-receipt",
          sceneId: "scene-crime-room",
          name: "Evidência 2: Recibo com Horário Falso",
          active: true,
          tags: ["evidence"],
          components: [
            { type: "TRANSFORM", x: 500, y: 250, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "📄 Examinar Recibo Rasgado" },
          ],
        },
        {
          id: "entity-btn-verdict",
          sceneId: "scene-crime-room",
          name: "Botão Concluir Investigação",
          active: true,
          tags: ["ui"],
          components: [
            { type: "TRANSFORM", x: 400, y: 450, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "⚖️ Ir para o Veredicto" },
          ],
        },
        {
          id: "entity-suspect-1",
          sceneId: "scene-verdict",
          name: "Acusar Contador Silva (Culpado)",
          active: true,
          tags: ["suspect"],
          components: [
            { type: "TRANSFORM", x: 300, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "Acusar Contador Silva" },
          ],
        },
        {
          id: "entity-suspect-2",
          sceneId: "scene-verdict",
          name: "Acusar Gerente Paula (Inocente)",
          active: true,
          tags: ["suspect"],
          components: [
            { type: "TRANSFORM", x: 500, y: 300, scaleX: 1, scaleY: 1, rotation: 0, zIndex: 1 },
            { type: "UI", elementType: "BUTTON", text: "Acusar Gerente Paula" },
          ],
        },
      ],
      variables: [
        { id: "var-evidenceCount", name: "evidenceCount", type: "NUMBER", initialValue: 0 },
        { id: "var-foundFingerprint", name: "foundFingerprint", type: "BOOLEAN", initialValue: false },
        { id: "var-foundReceipt", name: "foundReceipt", type: "BOOLEAN", initialValue: false },
      ],
      rules: [
        {
          id: "rule-inspect-fingerprint",
          name: "Inspecionar Impressão",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-ev-fingerprint" },
          conditions: [{ variableId: "var-foundFingerprint", operator: "EQUALS", value: false }],
          actions: [
            { type: "SET_VARIABLE", variableId: "var-foundFingerprint", value: true },
            { type: "ADD_VARIABLE", variableId: "var-evidenceCount", value: 1 },
            { type: "SHOW_TEXT", text: "Evidência Registrada: Impressões compatíveis com anel de formatura." },
          ],
        },
        {
          id: "rule-inspect-receipt",
          name: "Inspecionar Recibo",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-ev-receipt" },
          conditions: [{ variableId: "var-foundReceipt", operator: "EQUALS", value: false }],
          actions: [
            { type: "SET_VARIABLE", variableId: "var-foundReceipt", value: true },
            { type: "ADD_VARIABLE", variableId: "var-evidenceCount", value: 1 },
            { type: "SHOW_TEXT", text: "Evidência Registrada: Recibo adulterado emitido às 23h30." },
          ],
        },
        {
          id: "rule-go-verdict",
          name: "Avançar para Veredicto",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-btn-verdict" },
          conditions: [{ variableId: "var-evidenceCount", operator: "GREATER_THAN", value: 0 }],
          actions: [
            { type: "CHANGE_SCENE", targetSceneId: "scene-verdict" },
          ],
        },
        {
          id: "rule-accuse-culprit",
          name: "Acusar Culpado Verdadeiro",
          enabled: true,
          trigger: { type: "ON_CLICK", entityId: "entity-suspect-1" },
          conditions: [],
          actions: [
            { type: "SHOW_TEXT", text: "Veredicto Correto! Silva confessou o desvio de documentos. Caso Resolvido!" },
            { type: "END_GAME" },
          ],
        },
      ],
      scripts: [],
      inputActions: [
        { action: "INSPECT_EVIDENCE", keys: ["KeyE", "Space"], description: "Examinar Evidência" },
        { action: "OPEN_CASE_FILE", keys: ["KeyI", "Tab"], description: "Abrir Autos do Processo" },
        { action: "ACCUSE", keys: ["Enter", "KeyV"], description: "Emitir Veredicto / Acusação" },
      ],
      selectedSceneId: "scene-crime-room",
      selectedEntityIds: ["entity-ev-fingerprint"],
      updatedAt: new Date().toISOString(),
    }),
  },
];
