"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, CalendarDays, CheckCircle2, Cloud, Github, Link2, Mail, ShieldCheck, Unplug } from "lucide-react";
import { athenaIntegrationCenter, ATHENA_INTEGRATION_EVENT, type AthenaIntegration } from "@/lib/athena/integrations/integration-center";
import { googleCalendarSync, GOOGLE_CALENDAR_SYNC_EVENT } from "@/lib/athena/integrations/google-calendar-sync";
import { useVarynthStore } from "@/lib/store/useVarynthStore";
import { cn } from "@/lib/utils";
const icons = { "google-calendar": CalendarDays, gmail: Mail, "google-drive": Cloud, github: Github, "task-manager": CheckCircle2 };
type OAuthStatus = { configured: boolean; connected: boolean; missing: string[]; readOnly: boolean; workspaceEnabled?: boolean };
type DriveFile = { id: string; name: string; modifiedTime?: string; webViewLink?: string };
type GmailMessage = { id: string; subject: string; from: string; date?: string; snippet: string; url: string };

export function AthenaIntegrationCenter({ store }: { store: ReturnType<typeof useVarynthStore> }) {
  const [items, setItems] = useState<AthenaIntegration[]>([]); const [feedback, setFeedback] = useState<string>(); const [revision, setRevision] = useState(0); const [oauth, setOauth] = useState<OAuthStatus>(); const [syncing, setSyncing] = useState(false); const [workspaceSyncing, setWorkspaceSyncing] = useState(false); const [driveFiles, setDriveFiles] = useState<DriveFile[]>([]); const [gmailMessages, setGmailMessages] = useState<GmailMessage[]>([]);
  const refresh = () => { setItems(athenaIntegrationCenter.list()); setRevision((value) => value + 1); };
  const syncNow = async () => { setSyncing(true); try { const response = await fetch("/api/integrations/google-calendar/sync", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ windowDays: googleCalendarSync.settings().windowDays }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Falha na sincronização."); const result = googleCalendarSync.ingest(data.events, store.projects); athenaIntegrationCenter.verifyConnection("google-calendar", "OAuth próprio do VARYNTH"); athenaIntegrationCenter.recordSync("google-calendar", result.total); setFeedback(`Sincronização concluída: ${result.total} evento(s), ${result.conflicts} conflito(s).`); } catch (error) { const message = error instanceof Error ? error.message : "Falha na sincronização."; googleCalendarSync.recordFailure(message); setFeedback(message); } finally { setSyncing(false); } };
  const syncWorkspace = async () => { setWorkspaceSyncing(true); try { const [driveResponse, gmailResponse] = await Promise.all([fetch("/api/integrations/google-drive/sync", { method: "POST" }), fetch("/api/integrations/gmail/sync", { method: "POST" })]); const drive = await driveResponse.json(); const gmail = await gmailResponse.json(); if (!driveResponse.ok) throw new Error(drive.error || "Falha na leitura do Drive."); if (!gmailResponse.ok) throw new Error(gmail.error || "Falha na leitura do Gmail."); setDriveFiles(drive.files || []); setGmailMessages(gmail.messages || []); athenaIntegrationCenter.verifyConnection("google-drive", "Conta Google conectada"); athenaIntegrationCenter.verifyConnection("gmail", "Conta Google conectada"); athenaIntegrationCenter.recordSync("google-drive", drive.files?.length || 0); athenaIntegrationCenter.recordSync("gmail", gmail.messages?.length || 0); setFeedback(`Workspace atualizado: ${drive.files?.length || 0} arquivo(s) e ${gmail.messages?.length || 0} mensagem(ns).`); refresh(); } catch (error) { setFeedback(error instanceof Error ? error.message : "Falha na leitura do Google Workspace."); } finally { setWorkspaceSyncing(false); } };
  useEffect(() => { refresh(); let timer = 0; fetch("/api/integrations/google-calendar/status", { cache: "no-store" }).then(async (response) => { const status = await response.json(); if (!response.ok) throw new Error(status.error); return status as OAuthStatus; }).then((status) => { setOauth(status); if (status.connected && googleCalendarSync.settings().enabled) void syncNow(); if (status.connected) timer = window.setInterval(() => void syncNow(), googleCalendarSync.settings().intervalMinutes * 60_000); }).catch(() => setOauth({ configured: false, connected: false, missing: ["Serviço OAuth indisponível"], readOnly: true })); window.addEventListener(ATHENA_INTEGRATION_EVENT, refresh); window.addEventListener(GOOGLE_CALENDAR_SYNC_EVENT, refresh); return () => { if (timer) window.clearInterval(timer); window.removeEventListener(ATHENA_INTEGRATION_EVENT, refresh); window.removeEventListener(GOOGLE_CALENDAR_SYNC_EVENT, refresh); }; }, []);
  const settings = googleCalendarSync.settings(); const sync = googleCalendarSync.status(); const inbox = googleCalendarSync.inbox(); const connected = items.filter((item) => item.status === "conectada").length; void revision;
  const disconnect = async (item: AthenaIntegration) => { if (item.id === "google-calendar" && oauth?.connected) await fetch("/api/integrations/google-calendar/disconnect", { method: "DELETE" }); athenaIntegrationCenter.disconnect(item.id); if (item.id === "google-calendar") googleCalendarSync.removeImportedData(); setOauth((current) => current ? { ...current, connected: false } : current); setFeedback(`${item.name} desconectado.`); };
  return <div className="p-4"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 text-xs font-bold text-slate-200"><Link2 size={14} className="text-violet-400" /> Serviços externos</h3><p className="mt-1 text-[10px] text-slate-600">{connected} conexão(ões) registrada(s). Novas integrações começam somente em leitura.</p></div><span className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-2.5 py-1.5 text-[10px] text-emerald-300"><ShieldCheck size={11} className="mr-1 inline" /> Escrita externa bloqueada</span></div>{feedback && <div className="mb-3 rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-[11px] text-emerald-300">{feedback}</div>}
  <section className="mb-4 rounded-xl border border-blue-500/20 bg-blue-500/[0.03] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-xs font-bold text-slate-100">Sincronização OAuth do calendário</h4><p className="mt-1 text-[10px] text-slate-500">Leitura automática ao abrir e a cada {settings.intervalMinutes} minutos.</p></div><span className={cn("rounded px-2 py-1 text-[9px] font-bold uppercase", oauth?.connected && sync.state === "atualizada" ? "bg-emerald-500/10 text-emerald-300" : sync.state === "falhou" ? "bg-rose-500/10 text-rose-300" : "bg-amber-500/10 text-amber-300")}>{oauth?.connected ? sync.state.replaceAll("_", " ") : oauth?.configured ? "pronta para conectar" : "configuração necessária"}</span></div>
  {oauth && !oauth.configured && <div className="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/5 p-2 text-[10px] text-amber-300"><AlertTriangle size={11} className="mr-1 inline" /> Configure em <code>.env.local</code>: {oauth.missing.join(", ")}.</div>}{oauth?.configured && !oauth.connected && <a href="/api/integrations/google-calendar/connect" className="mt-3 inline-flex rounded-lg bg-blue-600 px-3 py-1.5 text-[10px] font-bold text-white">Conectar conta Google</a>}{oauth?.connected && <div className="mt-3 flex flex-wrap items-center gap-2"><button disabled={syncing} onClick={() => void syncNow()} className="rounded-lg bg-blue-600 px-3 py-1.5 text-[10px] font-bold text-white disabled:opacity-50">{syncing ? "Sincronizando…" : "Sincronizar agora"}</button><label className="text-[10px] text-slate-500">Intervalo <select value={settings.intervalMinutes} onChange={(event) => googleCalendarSync.saveSettings({ ...settings, intervalMinutes: Number(event.target.value) as 15 | 30 | 60 | 180 })} className="ml-1 rounded border border-[#303048] bg-[#09090f] px-2 py-1 text-slate-300"><option value={15}>15 min</option><option value={30}>30 min</option><option value={60}>1 hora</option><option value={180}>3 horas</option></select></label></div>}
  <div className="mt-3"><p className="text-[10px] font-bold text-slate-300">Caixa externa · {inbox.length} evento(s)</p>{!inbox.length && <p className="mt-1 text-[10px] text-slate-600">Nenhum evento recebido na janela atual.</p>}{inbox.map((event) => <div key={event.fingerprint} className="mt-2 rounded-lg border border-[#292940] bg-[#0b0b12] p-2.5"><div className="flex flex-wrap justify-between gap-2"><div><strong className="text-[11px] text-slate-200">{event.summary}</strong><p className="text-[9px] text-slate-500">{new Date(event.start).toLocaleString("pt-BR")}{event.conflictIds.length ? ` · conflito com ${event.conflictIds.length} evento(s)` : ""}</p></div>{!event.importedChronosId ? <button onClick={() => { const result = googleCalendarSync.importToChronos(event.id, event.suggestedProjectId, store.chronosEvents, store.addChronosEvent); setFeedback(result.success ? "Evento importado para o Chronos sem alterar o Google Calendar." : result.error); }} className="rounded-lg bg-violet-600/20 px-2 py-1 text-[9px] font-bold text-violet-300">Importar para Chronos</button> : <span className="text-[9px] text-emerald-400">Importado</span>}</div></div>)}</div><button onClick={() => { if (window.confirm("Remover todos os dados importados? Os eventos do Google não serão apagados.")) { googleCalendarSync.removeImportedData(); setFeedback("Dados importados removidos; o Google Calendar não foi alterado."); } }} className="mt-3 text-[9px] text-rose-400">Remover dados importados</button></section>
  {oauth?.connected && <section className="mb-4 rounded-xl border border-violet-500/20 bg-violet-500/[0.03] p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="text-xs font-bold text-slate-100">Gmail e Google Drive</h4><p className="mt-1 text-[10px] text-slate-500">Leitura protegida de mensagens recentes e metadados de arquivos; nenhum conteúdo é alterado.</p></div>{oauth.workspaceEnabled ? <button disabled={workspaceSyncing} onClick={() => void syncWorkspace()} className="rounded-lg bg-violet-600 px-3 py-1.5 text-[10px] font-bold text-white disabled:opacity-50">{workspaceSyncing ? "Atualizando…" : "Atualizar Workspace"}</button> : <span className="rounded bg-amber-500/10 px-2 py-1 text-[9px] font-bold uppercase text-amber-300">Ativação pendente</span>}</div>{!oauth.workspaceEnabled && <p className="mt-2 text-[10px] text-amber-300">Ative <code>VARYNTH_GOOGLE_WORKSPACE_ENABLED=true</code> depois de liberar as APIs Gmail e Drive no Google Cloud.</p>}{driveFiles.slice(0, 3).map((file) => <a key={file.id} href={file.webViewLink} target="_blank" rel="noreferrer" className="mt-2 block text-[10px] text-blue-300 hover:underline">Drive · {file.name}</a>)}{gmailMessages.slice(0, 3).map((message) => <a key={message.id} href={message.url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-[10px] text-violet-300 hover:underline">Gmail · {message.subject} — {message.from}</a>)}</section>}
  <div className="grid gap-2 sm:grid-cols-2">{items.map((item) => { const Icon = icons[item.id]; const isGoogle = item.id === "google-calendar"; return <article key={item.id} className={cn("rounded-xl border p-3", item.status === "conectada" ? "border-emerald-500/20 bg-emerald-500/[0.04]" : "border-[#292940] bg-[#11111b]")}><div className="flex items-start gap-3"><div className="rounded-lg bg-white/5 p-2"><Icon size={17} className={isGoogle ? "text-blue-400" : "text-slate-400"} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="text-xs font-bold text-slate-100">{item.name}</h4><span className={cn("rounded px-1.5 py-0.5 text-[9px] font-bold uppercase", item.status === "conectada" ? "bg-emerald-500/10 text-emerald-300" : "bg-slate-500/10 text-slate-500")}>{item.status}</span></div><p className="mt-1 text-[10px] text-slate-500">{item.description}</p>{item.accountLabel && <p className="mt-1 text-[9px] text-slate-600">{item.accountLabel}</p>}</div></div><div className="mt-3 rounded-lg border border-[#25253a] bg-[#09090f] p-2"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Permissões</p><div className="mt-1.5 flex flex-wrap gap-1">{Object.entries(item.permissions).map(([key, enabled]) => <span key={key} className={cn("rounded px-1.5 py-0.5 text-[9px]", enabled ? "bg-emerald-500/10 text-emerald-300" : "bg-slate-500/5 text-slate-600")}>{({ read: "Ler", create: "Criar", update: "Alterar", remove: "Excluir" } as Record<string,string>)[key]}: {enabled ? "sim" : "não"}</span>)}</div></div>{item.lastSyncAt && <p className="mt-2 text-[9px] text-slate-600">Última leitura: {new Date(item.lastSyncAt).toLocaleString("pt-BR")} · {item.importedItems} item(ns)</p>}{item.status === "conectada" && <button onClick={() => { if (window.confirm(`Desconectar ${item.name}?`)) void disconnect(item); }} className="mt-3 flex items-center gap-1 text-[10px] text-rose-400"><Unplug size={10} /> Desconectar</button>}</article>; })}</div></div>;
}
